openshift/jenkins

1/Dockerfile
1/Dockerfile.rhel7

@mfojtik @bparees please merge at your earliest convenience

switch to JDK 1.8 to fully enable OpenShift Java REST Client

---

1/contrib/jenkins/plugins.sh

@bparees a minor change to Jenkins plugin download that will show you `curl` error(s) when a plugin download failed.
Also a question whether we want to fail the docker build of the Jenkins image when 1 plugin failed to download or just build the image and display error summary (# plugins failed to download:)...
(my opinion is to fail)

Report curl output when plugin download failed

---

README.md

@bparees docs for the S2I build + removal of kubernetes plugin :-)

Update README to include S2I docs

---

1/Dockerfile.rhel7

fix rhel7 image to jdk1.8, link plugin rpm in jenkins startup path

---

1/contrib/openshift/base-plugins.txt

move to 105 of pipeline plugin

---

1/Dockerfile
1/Dockerfile.rhel7

fix a couple of 1.609 holdovers

---

1/contrib/openshift/base-plugins.txt

@bparees should be the last change needed to verify bugzilla 1294798

goto v1.0.6 of the plugin

---

1/contrib/openshift/base-plugins.txt

@bparees FYI 
this is for bugzilla 1299709; and in case it was a concern, I waited a week since I wrote the fix to see if other problems/fixes would come in before creating a new version of the plugin; of course, if you want to spread fix releases even further out let me know
thx

bump up to v.1.0.7 of plugin

---

1/contrib/openshift/configuration/jobs/OpenShift Sample/config.xml

@bparees PTAL - related to latest discussion in bugzilla 1293859 (new defect most likely coming); also, I believe you and I discussed removing this step before Christmas, but I had put it lower on the to-do list, not realizing the ramifications until seeing the results after 1293859 was resolved.

remove problematic deploy verify step from sample job

---

1/contrib/openshift/base-plugins.txt
1/contrib/openshift/configuration/jobs/OpenShift Sample/config.xml

@bparees - ptal
fyi - specifying values in the config.xml that were the same as the defaults for the plugin was redundant; plus, in my recent testing, I saw some odd behavior which could have been explained as the config.xml overriding fields I had saved.

move to v108 of plugin; remove some config.xml redundancy

---

1/Dockerfile
1/Dockerfile.rhel7
1/contrib/openshift/configuration/jobs/OpenShift Sample/config.xml
1/contrib/s2i/run

@bparees PTAL
@abhgupta @danmcp fyi - this PR among other things will add auto-tuning of the java heap based on available memory to the openshift jenkins image

tune java heap, fix sample job config, install rsync

---

1/Dockerfile.rhel7

Fix plugin installation in RHEL7 image

---

1/contrib/openshift/base-plugins.txt

move to v1.0.10 of the openshift pipeline plugin

---

1/contrib/openshift/base-plugins.txt

@bparees PTAL - more fixes for QE from tag image testing

move to v1.0.12 of openshift pipeline plugin

---

1/contrib/openshift/base-plugins.txt

move to v1.0.13 of pipeline plugin

---

1/contrib/openshift/base-plugins.txt

@bparees or @csrwng (assuming you have merge power for the jenkins repo as well) - pls hit the merge button when you get the chance.  Pulling in the the plugin version for the DSL additions for my card this sprint.

bump to v1.0.14 of openshift pipeline plugin

---

1/contrib/openshift/base-plugins.txt

@bparees or @mfojtik PTAL
a couple of bug fixes for QE and UI teams

goto v1.0.15 of pipeline plugin

---

1/contrib/openshift/base-plugins.txt

@bparees PTAL
this version has the fix for the small nit QE reported in trello last night

go to v1.0.17 of openshift pipeline plugin

---

1/contrib/openshift/base-plugins.txt

@bparees PTAL
Based on analysis documented in https://trello.com/c/r7oLwXJJ/958-3-jenkins-pipeline-plugins-rpm-packaging I've upgraded versions of a couple of plugins to match the dependencies listed in the latest version of the sync plugin.

more fabric induced plugin upgrades

---

1/Dockerfile.rhel7
1/contrib/jenkins/fix-permissions

Fixes https://github.com/openshift/jenkins/issues/101
@bparees PTAL

address double install with both hpi and jpi file being present

---

1/Dockerfile
1/Dockerfile.rhel7
1/contrib/openshift/base-plugins.txt

@bparees PTAL
@jimmidyson @rawlingsj FYI

various plugin upgrades for fabric

---

1/contrib/openshift/base-plugins.txt

goto v1.0.18 of openshift plugin

---

1/contrib/openshift/base-plugins.txt

@bparees PTAL
This is for the DSL `openShift..` to `openshift...` camel case related method name change requested by @smarterclayton

go to v1.0.19 of plugin

---

1/Dockerfile.rhel7
1/contrib/openshift/base-plugins.txt

@bparees PTAL
fyi - `make build TARGET=rhel7` passed on my ec2 instance.

add pipeline related rpms for rhel image

---

1/contrib/openshift/base-plugins.txt

move to v1.0.20 of openshift-pipeline

---

1/contrib/s2i/run

fixes https://github.com/openshift/jenkins/issues/117
@gabemontero ptal

set maven home to /var/lib/jenkins

---

slave-base/contrib/bin/generate_container_user

fixes https://github.com/openshift/jenkins/issues/130

allow nss to configure for uid 1001

---

1/contrib/openshift/configuration/jobs/OpenShift Sample/config.xml

clean up sample config; use default api endpoint and project

---

1/contrib/openshift/base-plugins.txt

fixes https://github.com/openshift/jenkins/issues/128

bump to latest k8s plugin

---

1/Dockerfile.rhel7
1/contrib/openshift/base-plugins.txt

pin matrix project for rhel; bump jenkins-plugin to 1.0.22

---

README.md

add note explaining how to replace existing plugins via s2i

---

README.md

@bparees per PR 156 my attempt to clarify the behavior with using oauth and permissions

clarifying oauth behavior

---

1/Dockerfile
2/Dockerfile
slave-base/Dockerfile

Updated the oc client tools to version 1.3 from 1.2.1

Updated oc client tools to version 1.3.

---

1/contrib/openshift/base-plugins.txt
2/contrib/openshift/base-plugins.txt

@bparees @csrwng @jupierce @oatmealraisin FYI

move centos to v1.0.23 of pipeline plugin

---

1/contrib/openshift/base-plugins.txt
2/contrib/openshift/base-plugins.txt

@bparees @csrwng @jupierce @oatmealraisin FYI
To minimize impact on Troy, current thinking is we'll get QE started on feature verification using the centos image, sort through any bugs on centos, then cut the RHEL RPMs / image and have QE do a regression.  They were amenable to that approach in the past.

pipeline plugin to v1.0.26, login plugin to v.0.2

---

2/Dockerfile.rhel7

fix jenkins2's bzcomponent

---

1/contrib/openshift/base-plugins.txt
2/contrib/openshift/base-plugins.txt

@bparees fyi
includes fix for bugzilla 1389482

bump login to 0.3

---

1/contrib/openshift/base-plugins.txt
2/contrib/openshift/base-plugins.txt

@bparees @csrwng fyi - has the plugin version for the fix @csrwng needs

goto v1027 of pipeline

---

1/contrib/openshift/base-plugins.txt
2/contrib/openshift/base-plugins.txt

pull plugin change for https://github.com/openshift/jenkins-plugin/issues/101 into jenkins images @bparees

v1.0.28 of pipeline plugin

---

1/contrib/openshift/base-plugins.txt
2/contrib/openshift/base-plugins.txt

pull in the fix for @csrwng 's "ec2" scenario 
@bparees fyi

goto v0.5 of login plugin

---

1/contrib/openshift/base-plugins.txt
2/contrib/openshift/base-plugins.txt

@bparees @jupierce this pulls in the recent PRs from @jupierce for QE bugzilla and PR testing

go to v1.0.29 of openshift pipeline

---

1/contrib/openshift/base-plugins.txt
2/contrib/openshift/base-plugins.txt

@bparees fyi ... creating the PR so I can ref in the bugzilla update re: cancelling jobs
when v1.0.30 is available, I'll remove the do not merge preface.

go to v1.0.30 of openshift pipeline

---

1/contrib/openshift/base-plugins.txt
2/contrib/openshift/base-plugins.txt

@bparees fyi
- npe fix from @jupierce 
- more debug, 1 more fix, from testing with @csrwng for problematic envs and defaulting to oauth (i.e. don't default if master does not provide us all the info we need)

v0.7 of login, v1.0.31 of pipeline, plugins

---

1/contrib/jenkins/kube-slave-common.sh
2/contrib/jenkins/kube-slave-common.sh

fixes https://github.com/openshift/jenkins/issues/189
@jim-minter ptal

remove duplicated remotefs definition

---

1/contrib/openshift/base-plugins.txt
2/contrib/openshift/base-plugins.txt

bump sync plugin to 0.0.17

---

1/contrib/s2i/run
2/contrib/s2i/run

See openshift/origin#11795 for rationale. 
@bparees @gabemontero ptal

Adding low memory profile for running Jenkins

---

1/cccp.yml
2/cccp.yml
slave-base/cccp.yml
slave-maven/cccp.yml
slave-nodejs/cccp.yml

This is for the purpose of building these containers on the
CentOS Container Pipeline.

Added cccp.yml files for building on container pipeline.

---

1/contrib/openshift/base-plugins.txt
2/contrib/openshift/base-plugins.txt

@bparees PTAL - a couple of bug fixes from @jupierce (including 1 bugzilla) for openshift-pipeline
@tdawson new RPM / brew-pulp image when you have the cycles please

goto v1.0.35 of openshift-pipeline

---

1/contrib/openshift/base-plugins.txt
1/test/run
2/Dockerfile
2/Dockerfile.rhel7
2/contrib/openshift/base-plugins.txt
2/test/run

This reverts commit 9ff112fbae7bc66c13def4091459b1dd47ba81cd.

re-bump to LTS v2.19.3, update related plugins, and add tests to confirm plugins load successfully

---

1/contrib/openshift/base-plugins.txt
2/contrib/openshift/base-plugins.txt

goto v1.0.36 of openshift-pipeline

---

1/Dockerfile
2/Dockerfile

- Use https Jenkins RPM repository (https://pkg.jenkins.io/redhat/)
- Correct jenkins2 OpenShift label

Couple of Dockerfile fixes

---

1/contrib/openshift/base-plugins.txt
2/contrib/openshift/base-plugins.txt

a few more bugzillas and personally discovered bugs / needs

goto v1.0.37 of openshift-pipeline

---

1/contrib/openshift/base-plugins.txt
2/contrib/openshift/base-plugins.txt

Need to wait until synced to Jenkins update centre

bump sync plugin to 0.1.4

---

README.md

Small README update to include info about jenkins 2.x support.

Added info for supported versions

---

1/contrib/openshift/base-plugins.txt
2/contrib/openshift/base-plugins.txt

bump pipeline plugin to 1.0.38

---

1/contrib/s2i/assemble
2/contrib/s2i/assemble

fixes https://github.com/openshift/jenkins/issues/212

support dot files in config dir

---

1/contrib/jenkins/kube-slave-common.sh
2/contrib/jenkins/kube-slave-common.sh

fixes https://github.com/openshift/jenkins/issues/220

tolerate empty imagestream annotations field for slave lookup

---

1/contrib/jenkins/kube-slave-common.sh
2/contrib/jenkins/kube-slave-common.sh

see https://github.com/openshift/origin/issues/12476
@bparees PTAL ... looked good in local testing

turn on tls, add sa cert, for k8s plugin

---

1/contrib/openshift/configuration/org.jenkinsci.main.modules.sshd.SSHD.xml
2/contrib/openshift/configuration/org.jenkinsci.main.modules.sshd.SSHD.xml

see https://github.com/openshift/origin/issues/12476
@bparees ptal - this is for disabling sshd per the discussion in the referenced issue

disable sshd in jenkins image

---

1/contrib/openshift/base-plugins.txt
2/contrib/openshift/base-plugins.txt

@bparees FYI
the login plugin update adds some debug that arose from some recent openshift online bugzilla's
the pipeline plugin update is the allowHostname and verify service fixes

goto 0.11 of login, 1.0.40 of pipeline

---

1/Dockerfile
2/Dockerfile
slave-base/Dockerfile

@bparees PTAL
Update `oc` to latest stable release

Update oc tool to 1.4.1

---

README.md

example has wrong path to for install-plugins script

README: fix script path in layered example

---

1/contrib/openshift/base-plugins.txt
2/contrib/openshift/base-plugins.txt

pull in openshift-client plugin into centos

---

1/Dockerfile
1/Dockerfile.rhel7
1/contrib/s2i/run
2/Dockerfile
2/Dockerfile.rhel7
2/contrib/s2i/run

allow for permission to see, easy enablement of, access logs

---

1/contrib/openshift/base-plugins.txt
2/contrib/openshift/base-plugins.txt

the plugin update includes the change for https://github.com/openshift/jenkins-client-plugin/issues/5
@csrwng @jupierce @bparees fyi

goto 0.9.1 of openshift-client

---

2/contrib/openshift/base-plugins.txt

Current version of BlueOcean is broken

Bump BlueOcean to version 1.0.0-b23

---

README.md

curation of plugin list in readme

---

1/contrib/openshift/base-plugins.txt
2/contrib/openshift/base-plugins.txt

@bparees FYI
@tdawson - can we use this PR to initiate the generation of a new RPM for the openshift-sync-plugin?  If not of course just let me know how you want us to register the ask.
However initiated, once that new RPM is ready, and after we merge https://github.com/openshift/jenkins/pull/238 tomorrow (march 3) we'll want to also have a new set of jenkins images created on brew-pulp to facilitate QE's testing of few features we have ready (and with 3.5 code freeze tomorrow march 3, we feel safe in doing so now)
thanks

bump sync plugin to 0.1.10

---

1/contrib/openshift/base-plugins.txt
2/contrib/openshift/base-plugins.txt

@spadgett @jwforres this will lead to the centos image on docker hub having the changes for the new log url annotations

bump sync and blueocean plugins

---

1/contrib/openshift/base-plugins.txt
2/contrib/openshift/base-plugins.txt

@bparees @csrwng fyi - v0.12 of the login plugin has the fix for Cesar's Jenkins / JJB change the root url cfg issue
@tdawson fyi - a new version of openshift-login to build an rpm for as part of 3.6

bump login plugin to v0.12

---

2/contrib/openshift/base-plugins.txt

@bparees @csrwng @jupierce @jorgemoralespou FYI ... per recent discussion in trello, adding declarative pipeline plugin to centos image

add pipeline-model-definition for declarative pipeline syntax

---

2/contrib/s2i/run
slave-base/contrib/bin/run-jnlp-client

java tuning tweaks per recent exchange with jboss folks
@bparees ptal

tweak java settings per jboss tuning script

---

1/contrib/openshift/base-plugins.txt
2/contrib/openshift/base-plugins.txt

bump sync pluging (configurable credential feature)

---

2/Dockerfile
2/Dockerfile.rhel7
2/contrib/openshift/base-plugins.txt

fixes https://github.com/openshift/jenkins/issues/279

set locale to en_US.UTF-8 by default

---

2/contrib/openshift/base-plugins.txt

bump blueocean to 1.0.1

---

1/contrib/openshift/base-plugins.txt
2/contrib/openshift/base-plugins.txt

for https://github.com/openshift/origin/issues/13983
@bparees @oatmealraisin @tdawson fyi

bump openshift client plugin version

---

README.md

move authentication content to login plugin readme

---

2/contrib/jenkins/install-plugins.sh

@bparees ptal
@openshift/devex fyi 
@smunilla - note, we supplied this script to @tdawson a few weeks ago to assist in building RPMs for the various Jenkins plugins.  You all most likely will want to cross reference these changes with what you have and apply as appropriate.

fix multiple issues with plugin dependency install script

---

1/contrib/jenkins/kube-slave-common.sh
2/contrib/jenkins/kube-slave-common.sh

This feature will be moved to the OpenShift Sync Plugin.
rebase of https://github.com/openshift/jenkins/pull/289

Removed ability to grab Image Streams at startup

---

1/contrib/openshift/base-plugins.txt
2/contrib/openshift/base-plugins.txt

more fixes for reported sync plugin bugs with new pod template support

bump sync plugin to v0.1.22

---

1/Dockerfile
2/Dockerfile

Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>
/cc @bparees

Update `oc` to v3.6.0-alpha.2

---

1/Dockerfile
2/Dockerfile

This reverts commit 5be52e2dfafafcb5a7c2d04e4a4a53ddbff4ddb9.
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>
/cc @bparees

Revert "Revert "Update `oc` to v3.6.0-alpha.2 (#318)" (#320)"

---

1/contrib/openshift/base-plugins.txt
2/contrib/openshift/base-plugins.txt

some upstream fixes for client, the multi cert fix from online ops for pipeline

bump pipeline to 1.0.47, client to 0.9.6

---

1/contrib/openshift/base-plugins.txt
2/contrib/openshift/base-plugins.txt

fixes https://github.com/openshift/origin/issues/14998

bump to sync plugin v0.1.23

---

1/Dockerfile.rhel7
2/Dockerfile.rhel7
hack/build.sh
slave-base/Dockerfile.rhel7
slave-maven/Dockerfile.rhel7
slave-nodejs/Dockerfile.rhel7

fixes https://github.com/openshift/jenkins/issues/313

switch rhel images to public base image

---

slave-base/Dockerfile.rhel7

https://bugzilla.redhat.com/show_bug.cgi?id=1477847

install the 32bit jvm in the slave base images

---

2/contrib/openshift/base-plugins.txt

Fixes https://github.com/openshift/origin/issues/15330
@openshift/devex

bump pipeline for pod exec fix

---

2/contrib/openshift/base-plugins.txt

Fixes https://github.com/openshift/jenkins/issues/316

bump blueocean to latest (1.1.4)

---

2/contrib/openshift/base-plugins.txt

bump sync plugin; small fixes, 1st post 3.6 feature req

---

2/contrib/openshift/base-plugins.txt

Fixes https://github.com/openshift/origin/issues/15685

bump sync plugin to address blueocean plugin api change

---

2/Dockerfile
slave-base/Dockerfile

fixes https://github.com/openshift/origin/issues/15656
@openshift/devex @siamaksade

bump centos images oc's to 3.6 GA

---

2/Dockerfile

Notable changes at: https://jenkins.io/changelog-stable/#v2.60.2

Move to 2.60.2 LTS

---

2/contrib/openshift/base-plugins.txt

Fixes https://github.com/openshift/jenkins/issues/355
@openshift/devex @jupierce @smunilla fyi
The plugin list with this change was:
```
Installed plugins:
ace-editor:1.0.1
authentication-tokens:1.1
blueocean-autofavorite:1.0.0
blueocean-commons:1.1.6
blueocean-config:1.1.6
blueocean-dashboard:1.1.6
blueocean-display-url:2.0
blueocean-events:1.1.6
blueocean-github-pipeline:1.1.6
blueocean-git-pipeline:1.1.6
blueocean-i18n:1.1.6
blueocean:1.1.6
blueocean-jwt:1.1.6
blueocean-personalization:1.1.6
blueocean-pipeline-api-impl:1.1.6
blueocean-pipeline-editor:0.2.0
blueocean-pipeline-scm-api:1.1.6
blueocean-rest-impl:1.1.6
blueocean-rest:1.1.6
blueocean-web:1.1.6
branch-api:2.0.9
cloudbees-folder:6.0.4
conditional-buildstep:1.3.1
config-file-provider:2.16.2
credentials-binding:1.12 …
```

update plugins per Aug 8 sec advisory

---

2/contrib/openshift/base-plugins.txt

part of https://github.com/openshift/jenkins-plugin/issues/147
including plugin update in image on docker hub @scoheb 
@openshift/devex @jupierce FYI
In addition to going to 1.0.49 of openshift pipeline, the plugin list as of my `make test VERSIONS=2` prior to PR submission:
```
Installed plugins:
ace-editor:1.0.1
authentication-tokens:1.1
blueocean-autofavorite:1.0.0
blueocean-commons:1.1.6
blueocean-config:1.1.6
blueocean-dashboard:1.1.6
blueocean-display-url:2.0
blueocean-events:1.1.6
blueocean-github-pipeline:1.1.6
blueocean-git-pipeline:1.1.6
blueocean-i18n:1.1.6
blueocean:1.1.6
blueocean-jwt:1.1.6
blueocean-personalization:1.1.6
blueocean-pipeline-api-impl:1.1.6
blueocean-pipeline-editor:0.2.0
blueocean-pipeline-scm-api:1.1.6
blueocean-rest-impl:1.1.6
blueocean-rest:1.1.6 …
```

bump openshift pipeline for okhttp class ldr isolation

---

2/contrib/openshift/base-plugins.txt

Fixes https://github.com/openshift/origin/issues/15823
@openshift/devex

bump pipeline for swaggerapi url fix

---

2/Dockerfile
2/Dockerfile.rhel7
slave-base/Dockerfile
slave-base/Dockerfile.rhel7

fixes https://github.com/openshift/jenkins/issues/361

loosen /var/lib/origin permissions for oc

---

2/contrib/openshift/base-plugins.txt

fixes https://github.com/openshift/jenkins-sync-plugin/issues/163
fixes https://github.com/openshift/jenkins-plugin/issues/151
among others, as in pulls in the requisite plug versions into the jenkins image 

bump sync, pipeline plugins

---

2/Dockerfile.rhel7

Plugins have been condensed into a single rpm to be installed
in the jenkins rhel image

Adding jenkins client plugin to jenkins rhel image

---

2/contrib/jenkins/install-plugins.sh

per recent email thread on #openshift-sme

only upgrade optional plugins if previously installed

---

2/contrib/openshift/base-plugins.txt

for https://github.com/openshift/jenkins-plugin/issues/153

bump pipeline for build verifier fix

---

2/contrib/openshift/base-plugins.txt

@openshift/devex fyi ... per request from @csrwng

add some plugins broken out from the aggregator

---

2/contrib/jenkins/kube-slave-common.sh

The .NET Core 2.0 jenkins slave image will be delivered to
the Red Hat Container Registry and is maintained upstream
separately in this repository:
https://github.com/redhat-developer/dotnet-jenkins-slave
This patch adds relevant kubernetes slave configuration for
the .NET Core 2.0 jenkins slave image so that jobs can be
scheduled on pods with .NET Core 2.0 installed. Jobs need
to be configured - via restrictions - to only run on nodes
with label expression "dotnet-20".
This PR resolves https://bugzilla.redhat.com/show_bug.cgi?id=1451403

Add .NET Core 2.0 kube-slave config.

---

slave-maven/Dockerfile
slave-maven/Dockerfile.rhel7

fixes https://github.com/openshift/jenkins/issues/383

install the 32bit jdk devel packages

---

2/contrib/openshift/base-plugins.txt

Fixes https://github.com/openshift/jenkins/issues/342
@openshift/devex @scoheb fyi
regression testing looks good

bump k8s to 1.0

---

slave-base/contrib/bin/run-jnlp-client

fixes https://github.com/openshift/jenkins/issues/391

fix core limit typo

---

2/contrib/openshift/base-plugins.txt

bump sync for linkage error

---

2/Dockerfile
2/Dockerfile.rhel7

fixes https://github.com/openshift/jenkins/issues/399

install a font package so jenkins monitoring plugin works

---

2/contrib/openshift/base-plugins.txt

@openshift/sig-developer-experience fyi to pick up some of @coreydaley 's recent fixes to the openshift client plugin deemed desirable for 3.7

bump openshift-client to 1.0.1

---

2/contrib/openshift/base-plugins.txt

minor fixes to login (ref to new event doc on errors) and client (fix raw bld step ui)
@openshift/sig-developer-experience

bump login to 1.0.0; bump client to 1.0.2

---

2/contrib/openshift/base-plugins.txt

centos change for https://github.com/openshift/jenkins/issues/415

bump pipeline-utility-steps to 1.5.1

---

CONTRIBUTING_TO_OPENSHIFT_PLUGINS.md
README.md
example-plugin-development-template.yaml

@openshift/sig-developer-experience fyi / ptal

document plugin dev/rel process; readme cleanup

---

2/contrib/s2i/run

Hi,
Currently the user can only override config.xml in the volume.
This fix/improvement allows him to override whatever configuration he needs to.
Regards,

Allow user to override more configuration than config.xml in the volume

---

2/contrib/openshift/base-plugins.txt

for https://trello.com/c/SGvNKyMM/1154-5-make-openshift-secrets-available-in-jenkins-as-credentials-jenkinsintegration

bump sync plugin for credential/secret change

---

2/Dockerfile

fixes https://github.com/openshift/jenkins/issues/439
fixes https://github.com/openshift/jenkins/issues/445

update to LTS 2.89.2

---

2/contrib/openshift/base-plugins.txt

see https://github.com/openshift/jenkins/pull/450

add comment around credentials-binding tracking

---

2/contrib/jenkins/install-plugins.sh

Fixes https://github.com/openshift/jenkins/issues/447

support version specific update centers

---

2/contrib/openshift/base-plugins.txt

Pulls in a bunch of fixes to openshift client plugin that came in over the last month
@openshift/sig-developer-experience @stevekuznetsov @jupierce fyi

bump client to 1.0.4 for myriad of holiday fixes

---

2/contrib/openshift/base-plugins.txt

@openshift/sig-developer-experience @stevekuznetsov fyi ... see step 3 of https://github.com/openshift/jenkins-client-plugin/pull/107

bump client plugin for more fixes

---

2/contrib/openshift/base-plugins.txt

Fixes https://github.com/openshift/jenkins/issues/472
@openshift/sig-developer-experience fyi 
note discussion in the issue, and that I ran our full plugin regression on this change

remove deprecated mutlipe-scm (which is cause NPE)

---

1/contrib/jenkins/plugins.sh
2/Dockerfile
2/Dockerfile.rhel7
2/contrib/jenkins/install-plugins.sh
2/test/run
2/test/s2i/plugins.txt
CONTRIBUTING_TO_OPENSHIFT_PLUGINS.md

The solution for issue #447 #460 was missing the JENKINS_UC_LATEST handling from https://github.com/jenkinsci/docker/blob/678f3ec669666bada2f448f9da3f33c4eb0417a9/install-plugins.sh#L218-L225
Also fixed some tab -> space indents

fix version specific update center handling

---

2/contrib/s2i/run
2/test/run
slave-base/contrib/bin/run-jnlp-client

allow escaped space in JENKINS_JAVA_OVERRIDES and JNLP_JAVA_OVERRIDES

---

README.md

Fixes https://github.com/openshift/jenkins/issues/481
@openshift/sig-developer-experience

update readme with command for displaying jenkins version from image

---

2/Dockerfile

Fixes https://github.com/openshift/jenkins/issues/487

update jenkins version to 2.89.3 for centos image

---

2/contrib/openshift/base-plugins.txt

Fixes https://github.com/openshift/origin/issues/18324
pulls in v1.0.2 which has the fix for above

bump sync plugin for origin ext test bug fix

---

2/contrib/openshift/base-plugins.txt

bump login plugin (condense/obfuscate printing of token)

---

2/contrib/openshift/base-plugins.txt

In this pull request I would like contribute with the project to update the latest stable versions of this list of plugins.

update plugins to Jenkins 2

---

2/contrib/openshift/base-plugins.txt

bump sync plugin for recent fix

---

2/contrib/openshift/base-plugins.txt

@openshift/sig-developer-experience fyi pulls in fix for https://bugzilla.redhat.com/show_bug.cgi?id=1549448

bump sync plugin for del bc fix

---

2/Dockerfile.rhel7

master version change for https://github.com/openshift/jenkins/issues/507

change version label to 3.9

---

2/Dockerfile.rhel7

@openshift/sig-developer-experience fyi 
3.7 version of fix for https://github.com/openshift/jenkins/issues/507

change version label to 3.7

---

2/contrib/openshift/base-plugins.txt

including the obfuscation of the token in the logs

pull in recent login plugin fixes

---

2/contrib/s2i/run
slave-base/contrib/bin/run-jnlp-client

Fixes https://github.com/openshift/jenkins/issues/522

use alternatives command on javac as well for maven

---

2/test/jenkins_test.go
openshift/templates/jenkins-ephemeral.json
openshift/templates/jenkins-persistent.json

port recent origin template changes around less aggressive timeouts

---

2/test/jenkins_test.go
pkg/docker/docker.go

@bparees ptal
this is the debug change to this repo's tests I mentioned to you earlier
highlights:
0) if the `s2i` invocation completes within a minute, nothing is printed
1) otherwise, it prints out the results from ps -ef within each container it finds
2) it prints out with nice formatting the json from `docker inspect`
like I mentioned, while it certainly would not have uncovered the docker flaw @jim-minter found, this changes would have ruled out a couple of our theories prior to that

add docker related debug around s2i test

---

openshift/templates/jenkins-ephemeral.json
openshift/templates/jenkins-persistent.json

match route timeout template updates in origin

---

Makefile
README.md
agent-maven-3.5/Dockerfile
agent-maven-3.5/Dockerfile.rhel7
agent-maven-3.5/README.md
agent-maven-3.5/cccp.yml
agent-maven-3.5/contrib/bin/configure-agent
agent-maven-3.5/contrib/bin/scl_enable
agent-maven-3.5/contrib/init.gradle
agent-maven-3.5/contrib/settings.xml
agent-maven-3.5/test/agent_maven_test.go
agent-nodejs-8/Dockerfile
agent-nodejs-8/Dockerfile.rhel7
agent-nodejs-8/cccp.yml
agent-nodejs-8/contrib/bin/scl_enable
agent-nodejs-8/test/agent_nodejs_test.go
hack/build.sh
slave-base/contrib/bin/configure-agent
slave-base/contrib/bin/run-jnlp-client

For https://trello.com/c/YQm7osws/1493-5-jenkins-slave-scl-dep-updatesjenkinsintegration

New agents

---

2/contrib/jenkins/kube-slave-common.sh
2/contrib/s2i/run

part 2 of 2 for https://trello.com/c/YQm7osws/1493-5-jenkins-slave-scl-dep-updatesjenkinsintegration
@openshift/sig-developer-experience fyi / ptal
we'll merge after https://github.com/openshift/jenkins/pull/537 merges and new images are available on dockerhub

update k8s plugin default pod templates to use new agent images

---

openshift/imagestreams/jenkins-centos7.json
openshift/imagestreams/jenkins-rhel7.json

bump jenkins to 3.10

---

2/Dockerfile
2/Dockerfile.rhel7
2/contrib/s2i/run
README.md

@bparees fyi - porting recent migration fix to 3.6

Migration fix 3.6

---

2/Dockerfile

revert lts bump until we sort out login plugin serialization

---

2/contrib/openshift/base-plugins.txt

bump sync plugin for watch logging and passive reconnect

---

2/Dockerfile
2/Dockerfile.rhel7
2/contrib/jenkins/kube-slave-common.sh
2/contrib/s2i/run

fixes https://bugzilla.redhat.com/show_bug.cgi?id=1548619

add verification for KUBE_CA contents

---

2/Dockerfile
2/Dockerfile.rhel7
slave-base/Dockerfile
slave-base/Dockerfile.rhel7

Fixes https://github.com/openshift/jenkins/issues/557
I did not universally alter all the chmod's as we have executables below the other directories

change /etc/passwd chmod to 664

---

2/Dockerfile
2/Dockerfile.rhel7
slave-base/Dockerfile
slave-base/Dockerfile.rhel7

Fixes https://github.com/openshift/jenkins/issues/554
@bparees ptal

add bzip2 to the images

---

agent-maven-3.5/Dockerfile.rhel7
agent-nodejs-8/Dockerfile.rhel7

@openshift/sig-developer-experience fyi / ptal
@adammhaile found some hiccups in the copy/paste changes in the Dockerfile.rhel7 for maven35 and nodejs8

fix some slave/agent conversion misses for rhel7

---

2/contrib/openshift/base-plugins.txt

pulls in fixes for various bugzillas/issues, as well as the optimizations stemming from work with perf/scalability

bump login/client/sync for recent fixes

---

2/Dockerfile.rhel7
2/contrib/openshift/base-plugins.txt
agent-maven-3.5/Dockerfile.rhel7
slave-base/Dockerfile.rhel7
slave-maven/Dockerfile.rhel7

skipping 1.0.11 of the sync plugin cause a useful addition from upstream came in after cutting 1.0.11 but before I got around to updating this image

bump client/sync plugins for recent changes

---

2/contrib/openshift/base-plugins.txt

bump client/sync plugins for recent fixes

---

2/contrib/openshift/base-plugins.txt

bump sync plugin for recent changes

---

README.md

Just a small documentation fix.

remove unnecessary tick marks

---

2/Dockerfile
2/Dockerfile.rhel7
2/contrib/s2i/run
agent-maven-3.5/Dockerfile
agent-maven-3.5/Dockerfile.rhel7
slave-base/Dockerfile
slave-base/Dockerfile.rhel7
slave-base/contrib/bin/run-jnlp-client
slave-maven/Dockerfile
slave-maven/Dockerfile.rhel7

for bug https://bugzilla.redhat.com/show_bug.cgi?id=1572710

do not enable i686 unless we are x86_64 based

---

2/contrib/openshift/base-plugins.txt

For https://trello.com/c/XBOXKjYA/1446-3-add-pod-tolerations-to-slave-pods-jenkinsintegration
also note, I've manually run our regression ext test suite against a jenkins image containing this new version of k8s plugin

bump k8s plugin to pick up our config via yaml change to the console

---

2/contrib/openshift/base-plugins.txt

bump login with inclusing of cancel permission

---

CONTRIBUTING_TO_OPENSHIFT_PLUGINS.md

minor tweaks based re-review, repo evolution

---

2/contrib/jenkins/kube-slave-common.sh

bump container cap to 100 for jenkins 1 and 2

---

2/Dockerfile
slave-base/Dockerfile
slave-maven/Dockerfile

@bparees @Gl4di4torRr fyi / ptal

similar to rhel, bypass on centos of rpm -V on java rpms

---

2/contrib/jenkins/kube-slave-common.sh

bump container cap to 100

---

2/contrib/jenkins/kube-slave-common.sh

bumping container limit to 100 for #637

bump container cap to 100 for jenkins 2

---

2/Dockerfile
slave-base/Dockerfile
slave-maven/Dockerfile

Pick 624 3.8

---

2/Dockerfile
slave-base/Dockerfile
slave-maven/Dockerfile

Pick 624 3.6

---

2/contrib/openshift/base-plugins.txt

See https://github.com/openshift/jenkins-client-plugin/pull/167

add lockable resource plugin for openshift client plugin

---

2/contrib/jenkins/kube-slave-common.sh
openshift/imagestreams/jenkins-rhel7.json

https://bugzilla.redhat.com/show_bug.cgi?id=1608729

switch to new rhel registry

---

2/contrib/openshift/base-plugins.txt

rhel updated in https://github.com/openshift/jenkins/pull/668 but we had to cancel that cause of my e2e foray

bump sync plugin

---

2/contrib/openshift/base-plugins.txt

https://jenkins.io/security/advisory/2018-07-30/#SECURITY-1016

🔒 Update kubernetes plugin for SECURITY-1016

---

2/contrib/openshift/base-plugins.txt

Fixes bug with [JENKINS-48149](https://issues.jenkins-ci.org/browse/JENKINS-48149)
/assign @grdryn 
/cc @gabemontero

Bump kubernetes plugin version

---

2/contrib/openshift/base-plugins.txt

bump sync for more secret/credential mapping permutations

---

2/contrib/s2i/run
slave-base/contrib/bin/run-jnlp-client

Fixes https://github.com/openshift/jenkins/issues/693

disable various override paths based on the associated env vars == false

---

README.md
openshift/templates/jenkins-ephemeral.json
openshift/templates/jenkins-persistent.json

URL of OKD is docs.okd.io now

---

openshift/imagestreams/jenkins-rhel7-ppc64le.json

Create ppc64le jenkins supported imagestream

Create ppc64le jenkins supported imagestream

---

2/contrib/openshift/base-plugins.txt

I think 1.70 has some [excellent changes](https://github.com/jenkinsci/job-dsl-plugin/wiki#release-notes). Please consider this.

Upgrade to job-dsl 1.70

---

2/contrib/s2i/run

Fix bash syntax errors

---

2/container.yml

create container.yaml for odcs multi-arch builds
@dorzel @adammhaile Please review.

create container.yaml for odcs multi-arch builds

---

2/contrib/openshift/base-plugins.txt

⬆ Upgrade pipeline plugins to latest

---

2/Dockerfile
2/contrib/openshift/base-plugins.txt

replacement of https://github.com/openshift/jenkins/pull/741
@bparees

Local upstream 741 copy

---

test-e2e/Dockerfile
test-e2e/tag-in-image.sh

this is going to need the openshift/release PR I'm about to submit
/hold

adjust jenkins e2e img env var name to new convention

---

2/Dockerfile
2/contrib/s2i/run

See the changelog page for more details:
https://jenkins.io/changelog-stable/

⬆ Upgrade Jenkins to latest LTS 2.138.4

---

2/Dockerfile
2/Dockerfile.rhel7
slave-base/Dockerfile
slave-base/Dockerfile.rhel7
slave-maven/Dockerfile
slave-maven/Dockerfile.rhel7

See https://jira.coreos.com/browse/ART-391
/assign @sosiouxme

add back in rpm -V for java rpms since now on 7.6 rhel

---

2/Dockerfile
2/Dockerfile.rhel7
agent-maven-3.5/Dockerfile
agent-maven-3.5/Dockerfile.rhel7
slave-base/Dockerfile
slave-base/Dockerfile.rhel7
slave-maven/Dockerfile
slave-maven/Dockerfile.rhel7

Rpm v stutter 310

---

agent-maven-3.5/Dockerfile
agent-maven-3.5/Dockerfile.rhel7

forgot the new agent mavens in 3.11 
/assign @bparees

add rpm -V back in for agent-maven as well

---

openshift/imagestreams/jenkins-rhel7.json

fix docker spec for rhel imagestream 2 tag

---

2/contrib/openshift/base-plugins.txt

in theory when the client plugin bump gets pushed to dockerhub, this PR's test job should pass
let's refrain from green buttoning this one immediately, see what happens

bump login plugin to move off of /oapi endpoints

---

openshift/imagestreams/jenkins-centos7.json
openshift/imagestreams/jenkins-rhel7.json

remove tags for jenkins-1-*

---

2/contrib/openshift/base-plugins.txt

https://jenkins.io/security/advisory/2019-01-28/

🔒 Upgrade plugins for Jenkins security advisory 2019-01-28

---

agent-nodejs-8/Dockerfile
agent-nodejs-8/Dockerfile.rhel7

fixes https://github.com/openshift/jenkins/issues/795

Fix issue #795

---

2/Dockerfile
2/Dockerfile.rhel7
slave-base/Dockerfile
slave-base/Dockerfile.rhel7

It is no longer created by default in the CLI image.

Take responsibility for creating the /var/lib/origin dir

---

plugin-lister/Dockerfile-plugin-lister
plugin-lister/lister.sh

add utility for getting the complete plugin list from base-plugins.txt

---

2/Dockerfile
2/Dockerfile.rhel7
agent-maven-3.5/Dockerfile
agent-maven-3.5/Dockerfile.rhel7
agent-nodejs-8/Dockerfile
agent-nodejs-8/Dockerfile.rhel7
slave-base/Dockerfile
slave-base/Dockerfile.rhel7

explicitly cite 3.11 in FROM clauses

---

2/Dockerfile
2/Dockerfile.rhel7
2/contrib/s2i/run
README.md
agent-maven-3.5/Dockerfile
agent-maven-3.5/Dockerfile.rhel7
slave-base/Dockerfile
slave-base/Dockerfile.rhel7
slave-base/contrib/bin/run-jnlp-client

@openshift/sig-developer-experience @smarterclayton fyi

remove 32 bit JVM

---

2/contrib/openshift/base-plugins.txt

Edit: removed the core LTS update.
~I've done these as separate commits, since the Jenkins core upgrade
doesn't actually fix any security issues, so I'm not sure if you want
to bother with it. :)~

Upgrade plugins

---

2/Dockerfile
2/Dockerfile.rhel7
2/contrib/openshift/base-plugins.txt
agent-maven-3.5/Dockerfile
agent-maven-3.5/Dockerfile.rhel7
slave-base/Dockerfile
slave-base/Dockerfile.rhel7

also addresses the recent discover documented in https://bugzilla.redhat.com/show_bug.cgi?id=1687553

🔒 Upgrade plugins for Jenkins security advisory 2019-03-06

---

2/contrib/openshift/base-plugins.txt

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1687553 with first commit

Plugin bumps

---

README.md

fixes around tbr, 3.11 sec advisories, agent default img

---

2/Dockerfile
2/Dockerfile.rhel7
slave-base/Dockerfile
slave-base/Dockerfile.rhel7

Run yum update to avoid package version mismatch between archs

run yum update to avoid package mismatch between archs

---

slave-base/Dockerfile.localdev

see https://github.com/openshift/jenkins/commit/6d112aab67e102db19aefdac46e2b262139a1041
this replaces https://github.com/openshift/jenkins/pull/811

remove outdated comment

---

2/contrib/openshift/base-plugins.txt

@openshift/sig-developer-experience @waveywaves @sthaha fyi

update requisite plugins for May21-2019 jenkins security advisory

---

2/contrib/openshift/base-plugins.txt

/assign @waveywaves 
when we `/assign` you to a PR we are asking that you review it .... 
if happy type in `/lgtm`

Bug 1720032: Jun112019 jenkins security advisory

---

2/contrib/openshift/base-plugins.txt

Bug 1720033: Jun112019 jenkins security advisory

---

2/contrib/openshift/base-plugins.txt

/hold
@openshift/sig-developer-experience FYI for 4.1

Bug 1719795: bump login/sync plugin versions for pom repository URL fix

---

README.md

fixes markdown syntax for bulltet lists, they were concatenated all to single line.

fix markdown syntax for bullet lists

---

2/contrib/openshift/base-plugins.txt

Bump jenkins-sync-plugin version to 1.0.39

---

2/contrib/jenkins/install-jenkins-core-plugins.sh

Bump jenkins version to 2.176.2

Bug 1731034: Bump jenkins version to 2.176.2

---

2/Dockerfile

Bumpin Jenkins version in centos image

Bug 1731024: Bumpin Jenkins version in centos image

---

2/Dockerfile.localdev
2/Dockerfile.rhel7
agent-maven-3.5/Dockerfile.localdev
agent-maven-3.5/Dockerfile.rhel7
agent-nodejs-8/Dockerfile.localdev
agent-nodejs-8/Dockerfile.rhel7
slave-base/Dockerfile.localdev
slave-base/Dockerfile.rhel7

Fixes https://github.com/openshift/jenkins/issues/894
@bparees fyi
/assign @akram @waveywaves

change maintainer in dockerfiles to Akram

---

2/contrib/openshift/base-plugins.txt

Bump openshift-sync version to 1.0.41.

Bump openshift-sync version to 1.0.41

---

2/contrib/openshift/base-plugins.txt

- jenkins-plugin-script-security-to-1.62
- workflow-cps to 2.73
- openshift-client version to 1.0.32
-  openshift-sync version to 1.0.41

Bug 1743279: Bump plugins versions

---

2/Dockerfile.localdev
2/Dockerfile.rhel7

Added label which gives the jenkins version.

Added label stating Jenkins Version

---

agent-nodejs-10/Dockerfile.localdev
agent-nodejs-10/Dockerfile.rhel7
agent-nodejs-10/README.md
agent-nodejs-10/cccp.yml
agent-nodejs-10/contrib/bin/configure-agent
agent-nodejs-10/contrib/bin/scl_enable
agent-nodejs-10/test/agent_nodejs_test.go

Add Nodejs 10 Agent 

---

2/contrib/jenkins/install-jenkins-core-plugins.sh

Fix yum clean by deleting /var/cache/yum/x86_64/7Server/

Fix yum clean by deleting /var/cache/yum/x86_64/7Server/

---

2/Dockerfile.localdev
2/contrib/jenkins/install-jenkins-core-plugins.sh
agent-nodejs-10/Dockerfile.localdev
agent-nodejs-10/Dockerfile.rhel7
agent-nodejs-8/Dockerfile.localdev
agent-nodejs-8/Dockerfile.rhel7
slave-base/Dockerfile.localdev
slave-base/Dockerfile.rhel7

use --disableplugin=subscription-manager with yum
to avoid error message: `This system is not registered with an entitlement server. You can use subscription-manager to register.`

Disable yum plugin subscription-manager

---

.gitignore
2/Dockerfile.localdev
2/Dockerfile.rhel7
Makefile
agent-maven-3.5/Dockerfile.localdev
slave-base/Dockerfile.localdev
slave-base/Dockerfile.rhel7

Remove all uses of dumb-init

---

agent-maven-3.5/Dockerfile.localdev
agent-maven-3.5/Dockerfile.rhel7
agent-maven-3.5/contrib/bin/configure-agent

Manage proxy configuration for the maven agent using http_proxy, https_proxy and no_proxy

Manage proxy configuration for the maven agent 

---

agent-nodejs-10/contrib/bin/configure-agent

Add ability to set proxy from env var for nodejs agent

---

2/Dockerfile.localdev
2/Dockerfile.rhel7
2/contrib/s2i/run
README.md

Adds proxy support for Jenkins master using http_proxy, https_proxy and no_proxy env variables

Adds proxy support for Jenkins master

---

2/contrib/s2i/run

Fix: no_proxy was already handled

---

2/contrib/openshift/base-plugins.txt

Bump kubernetes plugin to 1.18.2 to support proxies on OpenJDK 11

---

2/contrib/s2i/run

Enables 
-Djdk.http.auth.tunneling.disabledSchemes= -Djdk.http.auth.proxying.disabledSchemes=

Allows proxy tunnelling for OpenJDK11

---

agent-maven-3.5/Dockerfile.localdev
agent-maven-3.5/Dockerfile.rhel7
agent-nodejs-10/Dockerfile.localdev
agent-nodejs-10/Dockerfile.rhel7
agent-nodejs-8/Dockerfile.localdev
agent-nodejs-8/Dockerfile.rhel7
slave-base/Dockerfile.localdev
slave-base/Dockerfile.rhel7

Set env LC_ALL and LANG to en_US.UTF-8 in slave images

---

2/contrib/openshift/base-plugins.txt

Bug 1755812: Bump Sync Plugin to 1.0.42

---

2/contrib/openshift/base-plugins.txt

Bump openshfit-login-plugin to 1.0.21

Bug 1771337: Bump openshfit-login-plugin to 1.0.21

---

2/contrib/openshift/base-plugins.txt

Bump openshift-sync-plugin to 1.0.44

Bump openshift-sync-plugin to 1.0.44

---

2/Dockerfile

Bump jenkins version for 3.11 to 2.204.1

Bump jenkins version for 3.11

---

2/Dockerfile
2/Dockerfile.localdev
2/Dockerfile.rhel7
2/contrib/jenkins/install-jenkins-core-plugins.sh
2/contrib/jenkins/jenkins-common.sh
2/contrib/openshift/base-plugins.txt
2/contrib/s2i/run
HACKING.md
agent-maven-3.5/Dockerfile
agent-maven-3.5/Dockerfile.localdev
agent-maven-3.5/Dockerfile.rhel7
agent-nodejs-10/Dockerfile
agent-nodejs-8/Dockerfile
slave-base/Dockerfile
slave-base/Dockerfile.localdev
slave-base/Dockerfile.rhel7
slave-base/contrib/bin/generate_container_user
slave-base/contrib/bin/run-jnlp-client

Makes use of /etc/passwd g=rw not required
Updates Jenkins version
Updates Jenkins plugins

Bug 1793321: [4.2] Remove use of /etc/passwd and upgrade plugins versions

---

2/Dockerfile
2/Dockerfile.localdev
2/Dockerfile.rhel7
2/contrib/jenkins/install-jenkins-core-plugins.sh
2/contrib/jenkins/jenkins-common.sh
2/contrib/openshift/base-plugins.txt
2/contrib/s2i/run
HACKING.md
agent-maven-3.5/Dockerfile
agent-maven-3.5/Dockerfile.localdev
agent-maven-3.5/Dockerfile.rhel7
agent-nodejs-10/Dockerfile
agent-nodejs-8/Dockerfile
slave-base/Dockerfile
slave-base/Dockerfile.localdev
slave-base/Dockerfile.rhel7
slave-base/contrib/bin/generate_container_user
slave-base/contrib/bin/run-jnlp-client

Related to critical CVE
Makes use of /etc/passwd g=rw not required
Updates Jenkins version
Updates Jenkins plugins

Bug 1793322: [4.3] Remove use of /etc/passwd and upgrade plugins versions

---

2/Dockerfile
2/Dockerfile.rhel7
2/contrib/jenkins/jenkins-common.sh
2/contrib/openshift/base-plugins.txt
agent-maven-3.5/Dockerfile
agent-maven-3.5/Dockerfile.rhel7
slave-base/Dockerfile
slave-base/Dockerfile.rhel7
slave-base/contrib/bin/generate_container_user

Revert to use of nss_wrapper and update some plugins

Bug 1793324: Use nss_wrapper [3.11]

---

2/Dockerfile.localdev
2/Dockerfile.rhel7
2/contrib/jenkins/install-jenkins-core-plugins.sh

Bump Jenkins 2.204.2 as this has left behind

Bug 1813070: Bump Jenkins 2.204.2 [4.5]

---

2/Dockerfile.localdev
2/Dockerfile.rhel7
2/contrib/jenkins/install-jenkins-core-plugins.sh

Bump Jenkins 2.204.2
Various CVE flaws

Bug 1797143: Bump Jenkins 2.204.2 [4.4]

---

2/Dockerfile
2/Dockerfile.rhel7

Bump jenkins 2.204.2
Fix various CVEs

3.11 bump jenkins 2.204.2

---

OWNERS

Update OWNERS with Bugzilla Component

---

openshift/templates/jenkins-persistent-monitored.json

Bug 1836032: Fix kind in ServiceMonitor for persistent template

---

2/contrib/openshift/base-plugins.txt

Bug 1848216: CVE-2020-2182 jenkins-credentials-binding-plugin 1.0.23

---

2/contrib/openshift/base-plugins.txt

Update the client plugin version to the one with security fix

Bump openshift-client to 1.0.34

---

2/contrib/openshift/base-plugins.txt

Bump openshift-login-plugin to 1.0.25: proper oauth logout implementation

[head]Bug 1871084: oauth logout implementation

---

2/contrib/openshift/base-plugins.txt

cve-2020-2224 to cve-2020-2226: Bump matrix-auth plugin

[release-4.3] Bug 1857557: Bump matrix plugin

---

agent-maven-3.5/contrib/bin/scl_enable

- Updated the source scl_source enable rh-maven36

updating the scl_source enable from rh-maven35 to rh-maven36

---

2/contrib/openshift/base-plugins.txt

Also fixes https://bugzilla.redhat.com/show_bug.cgi?id=1881478

Bug 1881475: [3.11] Bump mailer and blueocean plugins

---

agent-maven-3.6/Dockerfile

Bug 1924811: Add jenkins maven36 image

---

2/Dockerfile.localdev
2/Dockerfile.rhel7
2/Dockerfile.rhel8
2/contrib/jenkins/install-jenkins-core-plugins.sh

This reverts commit 50112effa52caec214ca232bf6670be30245a055.

Bug 1950384: Revert "Update jenkins to 2.277.2"

---

agent-maven-3.6/Dockerfile.rhel7

The MAVEN_VERSION env var was incorrectly set to "3.5"

Bug 1973109: Fixed MAVEN _VERSION env var

---

smoke/features/jenkins-nodejs-agent.feature
smoke/features/persistent-nodejs-agent.feature
smoke/features/persistent-test.feature
smoke/features/steps/openshift.py
smoke/features/steps/plugins.py
smoke/features/steps/steps.py

- Adding feature to test the data persistence of jenkins persistent template
- Adding a function to get the jenkins master pod
- Adding function to exec into master pod and run command inside the pod to get the job count
- Refactored the nodejs agent test to check for the builds to complete
- Removed some unwanted code

Test the data persistence of jenkins persistent template

---

2/contrib/openshift/base-plugins.txt

Bug 1995727: bump sync plugin to 1.0.49

---

smoke/features/jenkins-ephemeral-without-oauth.feature
smoke/features/jenkins-teardown-ephemeral.feature
smoke/features/persistent-test.feature
smoke/features/steps/build_steps.py
smoke/features/steps/command.py
smoke/features/steps/debug.py
smoke/features/steps/delete_steps.py
smoke/features/steps/deployment_steps.py
smoke/features/steps/env_var_steps.py
smoke/features/steps/login_steps.py
smoke/features/steps/openshift.py
smoke/features/steps/project.py
smoke/features/steps/steps.py
smoke/features/steps/template_steps.py
smoke/features/steps/volume_steps.py
smoke/features/stress-test.feature
smoke/requirements.txt

Adds smoke test for JENKINS_PASSWORD
* perform connection to Jenkins using the Jenkins python client
* tests the change of the password
* refactors the testing framework by spliting it into several files
*

Smoke test for JENKINS_PASSWORD

---

2/contrib/openshift/base-plugins.txt

Hi @gabemontero ,
Here a test PR with the latest build. Let's see if it works well.

Bug 2016058: Bump openshift-sync-plugin to 1.0.51 and various dependant plugins

---

smoke/features/sidecar-pattern-jenkins.feature
smoke/samples/java-builder-cm.yaml
smoke/samples/nodejs-builder-cm.yaml

- Define the feature file for testing [JKNS-257](https://issues.redhat.com/browse/JKNS-257)

testing sidecar pattern for jenkins pod template

---

2/contrib/openshift/base-plugins.txt

Bug 2041888: bump openshift-sync to 1.0.53

---

smoke/features/steps/steps.py

- Removing reference to plugin class which was causing the smoke test not to run

removing reference to plugin class

---

2/contrib/openshift/base-plugins.txt
2/contrib/openshift/bundle-plugins.txt

- CVE-2022-25173 CVE-2022-25176 CVE-2022-25180: pin workflow-cps to
2660.vb_c0412dc4e6d
- CVE-2022-25174 CVE-2022-25177 CVE-2022-25178 CVE-2022-25181
CVE-2022-25182 CVE-2022-25183 : pin workflow-cps-global-lib to
564.ve62a_4eb_b_e039
- CVE-2022-25175 CVE-2022-25179: pin workflow-multibranch to
711.vdfef37cda_816
- CVE-2022-25184: pin pipleine-build-step to 2.16

Bug 2058752: 2022-02-15 Security Advisory

---

2/contrib/jenkins/install-plugins.sh

To have a consistent plugins list comparison, we now sort the plugins list alphabetically

Sort final plugins list alphabetically in `make plugins-list`

---

2/contrib/jenkins/install-plugins.sh
2/contrib/openshift/base-plugins.txt
2/contrib/openshift/bundle-plugins.txt

Enable supply-chain check for 4.10

Bug 2069134: [release-4.10] Enable supply-chain check

---

2/contrib/openshift/base-plugins.txt
2/contrib/openshift/bundle-plugins.txt

Mitigates:
- CVE-2022-29041
- CVE-2022-29048

Bug 2076257: Multiple Fixes

---

2/contrib/openshift/base-plugins.txt
2/contrib/openshift/bundle-plugins.txt

Mitigates:
- CVE-2022-27195
- CVE-2022-27196

Bug 2076430: Mitigate multiple CVEs

---

2/contrib/openshift/base-plugins.txt

[release-3.11] Bug 2076243: Multiple fixes

---

2/Dockerfile.localdev
2/Dockerfile.rhel7
2/Dockerfile.rhel8
2/contrib/jenkins/install-jenkins-core-plugins.sh
2/contrib/openshift/base-plugins.txt

Mitigates:
- CVE-2022-29041
- CVE-2022-29047
- CVE-2022-29048
- CVE-2022-27195
- CVE-2022-27196
Bump Jenkins to 2.319.3

[release-4.8] Bug 2076251: Mitigate multiple CVEs

---

2/Dockerfile.localdev
2/Dockerfile.rhel7
2/Dockerfile.rhel8
2/contrib/jenkins/install-jenkins-core-plugins.sh
2/contrib/openshift/base-plugins.txt

Mitigates:
- CVE-2022-29041
- CVE-2022-29047
- CVE-2022-29048
- CVE-2022-27195
- CVE-2022-27196
Bump Jenkins to 2.319.3

[release-4.7] Bug 2076250: Mitigate multiple CVEs

---

smoke/features/jenkins-teardown-ephemeral.feature
smoke/features/steps/build_steps.py
smoke/features/steps/delete_steps.py

- Some changes made as test are timing out on openstack cluster.

Bug 2088388: refactoring test for interop testing failures

---

2/Dockerfile.localdev
2/Dockerfile.rhel7
2/Dockerfile.rhel8
2/contrib/jenkins/install-jenkins-core-plugins.sh
2/contrib/openshift/base-plugins.txt

Mitigates:
- CVE-2022-29041
- CVE-2022-29047
- CVE-2022-29048
- CVE-2022-27195
- CVE-2022-27196
Bump Jenkins to 2.319.3

[release-4.6] Bug 2076249: Mitigate multiple CVEs

---

CONTRIBUTING.md

@openshift/openshift-team-build-api 
forgot to update the contributing guide with the recent e2e and payload removal instructions
also updated a couple of the imagestream refs as we get close to 4.11 shutdown to help illustrate the process
/assign @coreydaley 
/assign @akram

update contributing guide for e2e changes, payload removal and new process

---

openshift/imagestreams/jenkins-agent-base-centos.yaml
openshift/imagestreams/jenkins-rhel.json
openshift/imagestreams/jenkins-rhel.yaml

forgot to push my imagestream updates in #1454 
@openshift/openshift-team-build-api 
/assign @coreydaley

update imagestream image refs as needed based on recent CPaaS updates

---

2/Dockerfile.localdev
2/Dockerfile.rhel7
2/Dockerfile.rhel8
2/contrib/s2i/run

Revert xmlstarlet usage so that we can merge/backport multiple CVE fixes
Tracking in [Bug 2117742](https://bugzilla.redhat.com/show_bug.cgi?id=2117742)

Revert xmlstarlet usage

---

2/contrib/openshift/base-plugins.txt
2/contrib/openshift/bundle-plugins.txt

Bump jenkins-client-plugin to version 1.0.38

OCPBUGS-2184: Bump jenkins-client-plugin to version 1.0.38

---

2/contrib/openshift/base-plugins.txt
2/contrib/openshift/bundle-plugins.txt

OCPBUGS-914: Add maven plugin dependency

---

2/contrib/openshift/base-plugins.txt
2/contrib/openshift/bundle-plugins.txt

OCPBUGS-903: Bump openshift-login plugin to 1.0.29

---

2/contrib/openshift/base-plugins.txt
2/contrib/openshift/bundle-plugins.txt

[release-4.11] OCPBUGS-913: Add maven plugin dependency in base plugins

---

slave-base/Dockerfile.rhel8

[release-4.9] OCPBUGS-3173: Add glibc-langpack-en package in agent-base image

---

OWNERS

Update OWNERS to current team members

OCPBUGS-3692: [release-4.12] Update OWNERS

---

OWNERS

Update OWNERS to current team members

OCPBUGS-3697: [release-4.10] Update OWNERS

---

OWNERS

Update OWNERS to current team members

OCPBUGS-3698: [release-4.9] Update OWNERS

---

OWNERS

Update OWNERS to current team members

OCPBUGS-3760: [release-4.8] Update OWNERS

---

2/contrib/openshift/base-plugins.txt
2/contrib/openshift/bundle-plugins.txt

[release-4.10] OCPBUGS-912: Add maven plugin dependency in base plugins

---

2/contrib/openshift/base-plugins.txt
2/contrib/openshift/bundle-plugins.txt

[release-4.9]  OCPBUGS-911: Add maven plugin in base plugins

---

openshift/imagestreams/jenkins-agent-base-rhel.json
openshift/imagestreams/jenkins-agent-base-rhel.yaml
openshift/imagestreams/jenkins-rhel.json
openshift/imagestreams/jenkins-rhel.yaml

OCPBUGS-6579: Update sample imagestreams with latest 4.11 image using specific image tag reference

---

2/contrib/openshift/base-plugins.txt
2/contrib/openshift/bundle-plugins.txt

[release-4.10] OCPBUGS-900: Bump openshift login plugin to 1.0.29

---

2/contrib/openshift/base-plugins.txt
2/contrib/openshift/bundle-plugins.txt

[release-4.9] OCPBUGS-6711: Force git server to an earlier version

---

2/contrib/openshift/base-plugins.txt
2/contrib/openshift/bundle-plugins.txt

[release-4.10] OCPBUGS-4095: Required Plugin `workflow-multibranch`

---

2/contrib/openshift/base-plugins.txt
2/contrib/openshift/bundle-plugins.txt

Plugin `configuration-as-code` bumped to mitigate CVE-2022-42889

OCPBUGS-2541: configuration-as-code bumped to 1569.vb_72405b_80249

---

2/contrib/jenkins/kube-slave-common.sh
2/contrib/s2i/run

Fixes #1550 
Fixes #1545 
Fixes #1533 
Fixes #1535

OCPBUGS-11254: Fix several open issues on github

---

scripts/verify-jenkins.sh

Sample output:
```
$ SHA=650471d59f3aacf07a8a2ad58d52853a9aa3a653 sh scripts/verify-jenkins.sh 
[VERIFYING] Installed packages ...
- downloading Dockerfile.rhel8 ...                PASS
- checking dejavu-sans-fonts ...                  PASS
- checking wget ...                               PASS
- checking rsync ...                              PASS
- checking gettext ...                            PASS
- checking git ...                                PASS
- checking git-lfs ...                            FAIL
- checking tar ...                                PASS
- checking zip ...                                PASS
- checking unzip ...                              PASS
- checking openssl ...                            PASS
- checking bzip2 ...                              PASS
- …
```

Verify installed packages against Dockerfile.rhel8

---

2/go-init/main.go

git-init: fix NPE when killing a process

---

2/go-init/main.go

[release-4.13] OCPBUGS-21629: git-init: fix NPE when killing a process

---

2/go-init/main.go

[release-4.12] OCPBUGS-21617: git-init: fix NPE when killing a process

---

2/go-init/main.go

[release-4.11] OCPBUGS-21632: git-init: fix NPE when killing a process

---

2/contrib/openshift/base-plugins.txt
2/contrib/openshift/bundle-plugins.txt

Fixes the following CVE(s):
- CVE-2024-23900

OCPTOOLS-296: CVE-2024-23900

---

OWNERS

Signed-off-by: Satyam Bhardwaj <sabhardw@redhat.com>
rh-pre-commit.version: 2.2.0
rh-pre-commit.check-secrets: ENABLED

add avinal, ramessesii2, ayushsatyam146 to the Owners

---

.gitignore
2/contrib/openshift/base-plugins.txt
2/contrib/openshift/bundle-plugins.txt

Fixes the following CVE(s):
- CVE-2024-23899

OCPTOOLS-340: Fix CVE-2024-23899

---

2/contrib/openshift/base-plugins.txt
2/contrib/openshift/bundle-plugins.txt

Fixes the following CVE(s):
- CVE-2024-28149

OCPTOOLS-322: Fix CVE-2024-28149

---

OWNERS

Signed-off-by: Satyam Bhardwaj <sabhardw@redhat.com>
rh-pre-commit.version: 2.2.0
rh-pre-commit.check-secrets: ENABLED

[release-4.14] update OWNERS

---

2/Dockerfile.localdev
2/Dockerfile.rhel8
slave-base/Dockerfile.localdev
slave-base/Dockerfile.rhel8

Changes:
- Update JDK version to 21 in builder images

Update Java to JDK 21

---

2/Dockerfile.localdev
2/Dockerfile.rhel8
slave-base/Dockerfile.localdev
slave-base/Dockerfile.rhel8

Changes:
- Add JDK 17 to image

Add JDK 17

---

2/Dockerfile.localdev
2/Dockerfile.rhel8
2/contrib/s2i/run
BASIC_USAGE.md
CONTRIBUTING.md
openshift/templates/jenkins-ephemeral-monitored.json
openshift/templates/jenkins-ephemeral.json
openshift/templates/jenkins-persistent-monitored.json
openshift/templates/jenkins-persistent.json
slave-base/Dockerfile.localdev
slave-base/Dockerfile.rhel8
slave-base/contrib/bin/run-jnlp-client

- Remove java-11-openjdk and java-11-openjdk-headless from Dockerfiles

JKNS-529: Remove java 11 usage

---

.ci-operator.yaml
2/Dockerfile.rhel9
2/go-init/Dockerfile
slave-base/Dockerfile.rhel9
slave-base/go-init/Dockerfile

- update ubi7 to ubi9
Signed-off-by: Avinal Kumar <avinal@redhat.com>

JKNS-384: Update Jenkins base images to RHEL9

---

2/.konflux/Containerfile
2/contrib/jenkins/install-jenkins-core-plugins.sh

- Add Containerfile for onboarding openshift/jenkins to Konflux.
- Script to install jenkins.war updated to skip upstream RPM install if we source it from a Konflux-built artifact.

JKNS-463: Containerfile for Konflux

---

2/Dockerfile.rhel8
2/contrib/jenkins/install-jenkins-core-plugins.sh
2/contrib/openshift/configuration/init.groovy.d/oc-tools.groovy
slave-base/Dockerfile.rhel8

- Add oc-tools groovy script
- Modify Dockerfile to add oc and change base image
- Modify agent-base base image
- Modify install-jenkins-core-plugins.sh to change yum repo dir

konflux: Add multiple oc binaries
