openshift/jenkins

1/Dockerfile
1/Dockerfile.rhel7
1/contrib/openshift/base-plugins.txt
1/contrib/openshift/configuration/jobs/OpenShift Sample/config.xml
README.md
examples/master/configuration/jobs/sample-app-build/config.xml
examples/master/configuration/jobs/sample-app-deploy/config.xml
examples/master/configuration/jobs/sample-app-stage/config.xml

@mfojtik @bparees this is similar to PR https://github.com/openshift/jenkins/pull/46 but with some twists, but including the do not merge status for now.
Specifically:
1) I've renamed plugin configuration for @mfojtik 's master/slave examples 
2) I've add the openshift pipeline plugin to the base plugin list @mfojtik added with the above pull
3) I've converted the sample job to leverage a series of plugin steps vs. the shell script
In a momentary divergence from @mfojtik 's PR, I refrained the rhel image / rpm install changes for now.  I'll add them when then show up and I've had a chance to try them.

add plugin to centos image; apply plugin rename to config files; replace sample job with plugin

---

1/contrib/openshift/base-plugins.txt

@bparees moving the image to include the version of the plugin QE should run against for centos.  The 1.0.3 RPM for rhel has already been built.
(I was originally driving this change in the master/slave PR https://github.com/openshift/jenkins/pull/52 but am separating it out so we can get test going while we sort out the master slave stuff; the 1.0.3 changes are either generic fixes or the build parameter override feature, nothing specific to master/slave)

upgrade to 1.0.3 of plugin

---

1/contrib/openshift/base-plugins.txt

@bparees PTAL - fyi, we need to move to his version to address bugs seen by both upstream and QA since QA has started.  I've already pinged @tdawson about building the rpm for the plugin for the rhel image.  The centos image pulls directly from the update center, which is now hosting version 1.0.4.

bump to 104 of the plugin

---

1/Dockerfile
1/contrib/openshift/base-plugins.txt

@bparees @tdawson I found couple issues with the kubernetes plugin. I know that the plugin is available in brew and the test proves that it could be installed just fine, but:
1) The plugin requires "durable-task" plugin as an dependency. If this plugin is not installed, Jenkins will fail to initialize the kubernetes plugin with pretty ugly error. So we need to package that plugin as well and make it as an dependency for kubernetes plugin (and by doing that, we should bump the kubernetes plugin version ;-))
2) The kubernetes plugin require pretty recent version of the "credentials" plugin, which is a real problem. This plugin is currently **bundled** in the official Jenkins RPM. So it cannot be updated using "rpm". Kubernetes plugin needs it in order to be able to read the Service Account …

Add durable-task and pin the credentials plugin

---

1/contrib/openshift/base-plugins.txt

@bparees @mfojtik FYI / PTAL
I've created v1.0.9 of the openshift pipeline plug-in up at then jenkins update center.
The most important change, which lead to my cutting a new version now so we could include in official releases if we deem appropriate, was the issue I emailed about last week with getting the image's mounted cert into the java trust store used by the openshift-restclient-java component.  As far as SSL/TLS goes, we were basically always in "skip TLS" mode (well, skip TLS plus a couple of minor verifications I could do at the plugin level).  With this version, the cert is now getting added into a java x509 trust store maintained by the plugin and the communication with the server is getting fully validated from a TLS perspective (I was able to validate both good certs pass …

bump to v109 of openshift pipeline plugin

---

1/contrib/openshift/base-plugins.txt

@bparees PTAL
This version has 2 bugzilla fixes from QE testing of my 2 plugin cards this sprint, as well as an upstream ask around exiting failed builds more expediently, followed by an NPE fix that @sspeiche found.

move to 1.0.11 of openshift pipeline plugin

---

1/contrib/openshift/base-plugins.txt

@bparees PTAL (though given your PTO certainly wait until next week if you like ;-) )
Note:  technically, I only need the `# Pipeline plugin - https://wiki.jenkins-ci.org/display/JENKINS/Pipeline+Plugin` list of plugins for the [new DSL for OpenShift Pipeline Plugin](https://trello.com/c/jOEuMkze/924-5-provide-jenkins-dsl-for-openshift-pipeline-plugin-steps-plug-points), but I went ahead and added the complete list from https://github.com/fabric8io/openshift-jenkins-s2i-config/blob/master/plugins.txt, except for the fact that our image was already pulling in credentials:1.24 (where the plugins.txt from the fabric folks was pulling in credentials:1.22).
@jimmidyson @rawlingsj - FYI

add workflow / fabric related plugins

---

1/contrib/openshift/base-plugins.txt

@mfojtik ptal / merge
@bparees @jwforres FYI - the upgrade to 2.2 is motivated by https://github.com/fabric8io/openshift-jenkins-sync-plugin/issues/57
My regression testing of the new openshift pipeline DSL held up with v2.2 of workflow-cps

go to workflow-cps 2.2 for UI development

---

1/contrib/openshift/base-plugins.txt

@bparees PTAL
this should be the last of the changes based on QE's testing of the centos image for the plugin DSL card based on their feedback in trello.

goto to v1.0.16 of plugin

---

1/contrib/openshift/base-plugins.txt

@bparees ptal
i was able to verify that the associated rhel rpm for this version is picked up during rhel build

move to v1.0.21 of pipeline plugin

---

1/contrib/openshift/configuration/config.xml.tpl

Adds view permission for the user or groups named "view".
@gabemontero there's no distinction between users and subjects.  This is going to create shadowing risks.  You should consider what you're doing.

add read permission to viewers

---

1/Dockerfile.rhel7

Bug 1365767
Bugzilla link https://bugzilla.redhat.com/show_bug.cgi?id=1365767
Detailed explanation
The chown in Dockerfile.rhel7 did not traverse the links and update
/usr/lib64/jenkins/*hpi
@bparees PTAL

jenkins image: fix permissions fix on rhel build

---

1/contrib/jenkins/kube-slave-common.sh

It works only for service account in the same namespace, but that is the limitation of kubernetes cloud plugin in 0.8 as metioned in https://github.com/openshift/jenkins/pull/143#issuecomment-241013800
I have considered [using it from env. variable](https://github.com/openshift/jenkins/pull/143#issuecomment-241089186), but this seems architecturally cleaner. I don't like coupling it to the template and it should be the same service account for master and slaves.
@bparees PTAL

Add serviceaccount auto-configuration for slaves

---

slave-base/contrib/bin/run-jnlp-client

When launching slave it is likely to hit errors like non-trusted jenkins server certificate.
Without the `-S` option, curl exits with some status but no indication as to
what the problem actually is. `-S` option only tells curl to print things when
an error is hit. Not output will be present (as before) when things go smoothly.
btw, how do I take care of bad certificate? Any way I can setup server cert
so it is accepted without modifying Dockerfile?

show download error if any

---

1/contrib/openshift/base-plugins.txt
2/contrib/openshift/base-plugins.txt

@bparees fyi
v0.6 of openshift-login includes debug around problems accessing the master for defaults when within a pod that we discussed in scrum, as well as closing a window for improperly defaulting to oauth that surfaced when helping out @oatmealraisin this morning.

go to v0.6 of openshift login

---

1/contrib/openshift/base-plugins.txt
2/contrib/openshift/base-plugins.txt

v0.7 somehow missed a previous fix around inadvertent defaulting; also, 1 more small tweak in the logging was needed to clearly diagnose the issue in @csrwng 's env
with both changes, we were able to a) successfully *NOT* default to oauth, b) confirm a config/permissions issue existed in @csrwng 's env
@bparees fyi

go to v0.8 of login plugin

---

1/contrib/openshift/base-plugins.txt
2/contrib/openshift/base-plugins.txt

pulls in the fix for https://github.com/openshift/jenkins-openshift-login-plugin/issues/5
@bparees @jim-minter FYI 
@tdawson let's wait for @jim-minter to confirm this fix works for him before worrying
about the rpm / image respin.

bump login to v0.9

---

1/contrib/openshift/base-plugins.txt
1/contrib/openshift/configuration/jobs/OpenShift Sample/config.xml
2/contrib/openshift/base-plugins.txt
2/contrib/openshift/configuration/jobs/OpenShift Sample/config.xml

@bparees PTAL
- bump pipeline plugin to 1.0.33 for a small regression introduced with the bugzilla fix for scaling beyond 1 replica
- updated sample job to adjust to the change in behavior with the example admin app's ICT going to auto=false
- included adding some of the newer fields to the config objs
@tdawson fyi v1.0.33

update sample now that sample ICT is false; bump pipeline plugin

---

1/contrib/openshift/base-plugins.txt
1/test/run
2/contrib/openshift/base-plugins.txt
2/test/run

pulls in the openshift-pipeline fix for https://bugzilla.redhat.com/show_bug.cgi?id=1395555 for jenkins-*-centos7
@bparees FYI
@tdawson we'll need a new RPM for v1.0.34 of openshift-pipeline (the other RPMs are up to date) and a respin of jenkins-*-rhel7 on brew-pulp - thanks
@dongboyan77 FYI

go to v1.0.34 of openshift-pipeline

---

2/Dockerfile

Reverts openshift/jenkins#200
this appears to have caused a mess.  I haven't checked yet if the rhel image has the same/similar issues.  @tdawson fyi.
```
SEVERE: Failed Loading plugin Favorite v2.0.2 (favorite)
java.io.IOException: Favorite v2.0.2 failed to load.
- Matrix Project Plugin v1.7 is older than required. To fix, install v1.7.1 or later.
at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:621)
at hudson.PluginManager$2$1$1.run(PluginManager.java:516)
at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
at jenkins.model.Jenkins$7.runTask(Jenkins.java:1038)
at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
at …
```

Revert "bump to LTS v2.19.3"

---

1/contrib/jenkins/kube-slave-common.sh
2/contrib/jenkins/kube-slave-common.sh

The current `kube-slave-common.sh` script uses a regular expression to strip a service account name like 'system:serviceaccount:namespace:default' down to just the username, 'default'. However, the existing regex does not support all possible namespace/project names. Namely, a namespace like 'my-namespace' is a valid resource name, but '-' does not match the expression used in that script. The regex in this change more closely resembles the one used to validate namespace names in k8s, (`[a-z0-9]([-a-z0-9]*[a-z0-9])?`)
We can't quite match exactly what k8s uses because `expr` doesn't support extended regular expressions, but this is very close.
@bparees

Update to oc whoami regex to not exclude project names containing '-'.

---

README.md

@bparees PTAL
when prepping for the bearer token access feature, noticed the description around the current browser based access for oauth was outdated.  This pull fixes that.  I'll then submit a separate pull once the bearer token access feature drops for those additions.

some README corrections/clean up wrt oauth vs. jenkins login

---

1/contrib/openshift/base-plugins.txt
2/contrib/openshift/base-plugins.txt

A bug in  openshift-sync plugin breaks Jenkins pipeline builds:
Intermittent: Pipeline builds stop working after a while #113
https://github.com/openshift/openshift-jenkins-sync-plugin/issues/113
Bug 1406306 - jenkinsPipelineStrategy BC won't work after master/node services restart and Jenkins pod will log "SEVERE: Failed to update job"
https://bugzilla.redhat.com/show_bug.cgi?id=1406306
It's fixed in openshift-sync plugin v0.1.7 https://github.com/jenkinsci/openshift-sync-plugin/releases/tag/v0.1.7
This PR updates the version openshift-sync plugin in base-plugins to 0.1.7

Updates openshift-sync plugin to 0.1.7, which fixes bugs that break Jenkins pipeline builds

---

1/contrib/openshift/base-plugins.txt
2/contrib/openshift/base-plugins.txt

@bparees PTAL - a couple of github issue / bugzilla fixes.
@tdawson - FYI - for the bugzilla, we'll need a 1.0.42 RPM for openshift-pipeline and versions of the openshift jenkins-*-rhel7 built with that RPM out on brew-pulp for defect verification.  I'll tag you in the bugzilla in question.
thanks

goto v1.0.42 of openshift-pipeline

---

2/contrib/openshift/base-plugins.txt

@bparees  - more scm-api churn on v2
also, jquery-detached failed to download in v2 testing.  Uncovered that
a) https://updates.jenkins-ci.org/download/plugins/jquery-detached-plugin now gets a 404 / not found
b) per https://wiki.jenkins-ci.org/display/JENKINS/jQuery+Detached+Plugin you should not install this plugin directory
Interestingly, even after clearing my docker image cache, jquery-detached still downloaded and built with v1.  At first blush don't understand why.  We'll see how subsequent tests turn out.

more jenkins plugin churn (scmapi, jquery-detached)

---

2/contrib/openshift/base-plugins.txt

Version 2.5 of the plugin breaks the openshift client plugin
Requires change from https://github.com/openshift/jenkins/pull/248

Bump Pipeline Shared Groovy Libraries Plugin to version 2.6

---

1/contrib/openshift/base-plugins.txt
2/contrib/openshift/base-plugins.txt

@bparees fyi for https://trello.com/c/h6NSFQgk/1052-5-allow-env-variables-on-pipeline-buildconfigs-techdebt-pipeline-integration
`make test VERSIONS=2` worked locally for me after clearing out my jenkins image cache ... let's see how stable upstream plugin dependencies are

bump sync pluging to 0.1.8

---

1/Dockerfile
1/Dockerfile.rhel7
1/contrib/jenkins/jenkins-common.sh
1/contrib/s2i/run
1/test/run
2/Dockerfile
2/Dockerfile.rhel7
2/contrib/jenkins/jenkins-common.sh
2/contrib/s2i/run
2/test/run
Makefile
hack/build.sh
slave-base/Dockerfile
slave-base/Dockerfile.rhel7
slave-base/contrib/bin/generate_container_user
slave-base/contrib/bin/run-jnlp-client

@bparees PTAL
*** NOTE *** 
I wanted to see what it would take to use `alternatives` to manage the java version as the `1001` user, since `alternatives` is a more complete switch (handles everything, not just the `java` binary).
Here are the updates for centos and jenkins v1 and v2.
Based on how the review goes, I'll circle back and start looking into updating the rhel image.

add java i386 arch

---

2/contrib/openshift/base-plugins.txt

I tried building this image from a dockerfile into OpenShift with the latest Jenkins image and received an error that the pipeline groovy libraries needed to be updated to 2.7.

Update Pipeline Groovy libraries

---

2/contrib/openshift/base-plugins.txt
2/test/run

@tdawson @bparees the origin extended tests and jenkins v2 images test both look good.  I was also able to confirm from the make logs that the plugins removed from the list that we care about were in fact still downloaded (subversion wasn't but I was wondering if we really need that one)
When all is said and down then, I suspect the larger list for v1 jenkins will remain constant for plugins we don't own, while the smaller list of plugins we don't own for v2 can still change.  
Also, for @bparees and I, I believe this will shield from the scenario where a plugin changes dependency versions but the plugin itself does not change its version.  Since we are only including the "parent" plugins now.
I won't change the rhel Dockerfile until a) this PR merges, and b) we confirm with @tdawson that …

reduce v2 plugin list, list parent plugins download

---

2/contrib/s2i/run
2/test/run
README.md

Add support for an environment variable (INSTALL_PLUGINS) that allows
installing a set of plugins on image startup. The format of the variable
is a set of comma-separated strings of the form [plugin-id]:[version].
Example:
INSTALL_PLUGINS=groovy:1.30,github-pr-comment-build:1.1
When used with persistent storage, plugin download/installation would
only happen the very first time the image is run.

Optionally install plugins on startup

---

hack/build.sh

I was having problems building the Docker image.
Here is how I tried:
```
$ git clone git@github.com:openshift/jenkins.git openshift-jenkins
Cloning into 'openshift-jenkins'...
.......
Resolving deltas: 100% (786/786), done.
$ cd openshift-jenkins
$ docker images
<NOTHING>
$ make build TARGET=centos7 VERSION=2
.......
.......
Successfully built 22ba8f27048c
$ docker images
openshift/openshift-2-centos7      latest              22ba8f27048c        24 seconds ago      1.25 GB
```
`build.sh` script is doing some magic based on the directory name. However, the target image will have a weird name if the sources are checked out in a directory named differently.
Following works (when I don't specify the clone target dir):
```
$ git clone git@github.com:openshift/jenkins.git
Cloning into …
```

Consistent naming for Docker images built

---

2/contrib/openshift/base-plugins.txt

pipeline-model-definition dependency download was failing because of cloudbees plugin name change ... ref:  https://wiki.jenkins-ci.org/display/JENKINS/CloudBees+Docker+Workflow+Plugin
@bparees @oatmealraisin @tdawson FYI

bump pipeline-model-def to account for cloudbees plugin name change

---

1/contrib/openshift/base-plugins.txt
2/contrib/openshift/base-plugins.txt

@bparees @tdawson FYI
@jim-minter - this will pull into the openshift jenkins centos image the sync plugin change to be more prudent on when bc's are updated

bump sync to 0.1.14

---

1/contrib/openshift/base-plugins.txt
2/contrib/openshift/base-plugins.txt

@openshift/devex FYI
@smunilla ptal - we'll need new 3.6 based RPMs built for these new versions of the openshift pipeline, client, and sync plugins

bump openshift plugins for various fixes

---

1/Dockerfile
2/Dockerfile

Reverts openshift/jenkins#318
@stevekuznetsov have to revert this due to https://github.com/openshift/origin/issues/14821
/cc @gabemontero

Revert "Update `oc` to v3.6.0-alpha.2"

---

1/contrib/openshift/base-plugins.txt
2/contrib/openshift/base-plugins.txt

v0.1.24 of the sync plugin brings in the setting of user-agent of the underlying http client that came out of the recent diagnosis for the us-east prod cluster struggles
@bparees - I'm assuming we want this in 3.6 - that your opinion?
@bparees @jupierce @smunilla - if so, we need to build a 3.6 rpm and a new 3.6 jenkins image, and presumably consider whether the resulting image is what goes into the pipeline for the upcoming upgrade of the jenkins image running in us-prod east .... what is everyone thoughts?

bump sync plugin to 0.1.24

---

2/contrib/openshift/base-plugins.txt

for https://bugzilla.redhat.com/show_bug.cgi?id=1473329 and https://bugzilla.redhat.com/show_bug.cgi?id=1475867
@bparees with v1 deprecated in 3.6, should we continue to bump our plugins in the v1 image (this PR does not currently)
@smunilla @jupierce - don't know if the 3.6 release coming out means for your immediate workload, but both a customer and the online tier will want the RPM update for sync plugin minimally as part of post 3.6.  The specifics should be tracked in the bugzillas.  Thanks.

bump sync to 0.1.25 for bugzillas

---

1/contrib/jenkins/kube-slave-common.sh
2/contrib/jenkins/kube-slave-common.sh

- This fix helps determine JENKINS_URL during initial deployment regardless of what
the JENKINS service is called.
- This needs https://github.com/openshift/origin/pull/16183

Support cases where Jenkins service name is not Jenkins

---

2/contrib/s2i/assemble
2/contrib/s2i/run

I've added "shopt -s dotglob" in s2i/run as well, such that e.g. ${JENKINS_INSTALL_DIR}/configuration/.gitconfig file will be copied as well.
Furthermore, I moved the "shopt -s dotglob" command in s2i/assemble to the top, since it changes the global state of the bash process and should not be hidden in the code. As a consequence, hidden files from ${JENKINS_INSTALL_DIR}/plugins will also be copied, but I can't think of any harm there.

include hidden files when copying and moving in s2i/run

---

2/contrib/s2i/run

The environment substitution process in s2i/run is quite handy. At the moment, it only works for the config.xml and credentials.xml file, but in my case it would be great if it would also fill in environment variables in other configuration files, e.g.
* hudson.plugins.sonar.SonarGlobalConfiguration.xml
* proxy.xml
* config.xml of seed jobs
I've extended s2i/run to substitute all *.tpl files in the tree under /opt/openshift/configuration, during the initial configuration run of Jenkins. I took care not to modify the special cases for the config.xml and credentials.xml files.

template all *.tpl files in the Jenkins configuration

---

2/contrib/openshift/base-plugins.txt

pulls in some fixes for @csrwng and @scoheb 
@jupierce I'll post when the test job completes the latest plugin list that gets dumped by our test job for jenkins rhel image updating

bump sync plugin to 0.1.29

---

2/contrib/openshift/base-plugins.txt

downgrading fabric8 for now until a 3.6.1 and later 3.7.0-alpha are cut to include fix for issue seen in https://github.com/openshift/origin/issues/16501 and https://github.com/openshift/jenkins-sync-plugin/issues/173

bump sync for openshift/origin field selector workaround

---

2/contrib/openshift/base-plugins.txt

pulling in a minor refinement to the client plugin, then officially moving to 1.0.0 as part of this no longer being experimental in 3.7
@openshift/devex @jupierce FYI

bump client plugin to 1.0.0 as part of GA in 3.7

---

2/contrib/jenkins/install-plugins.sh

Fixes https://github.com/openshift/jenkins/issues/390
thx for the `bash` assist @bparees 
validated with both dos and unix files
`dos2unix` was not available in the openshift/origin image

clean up dos file carriage returns

---

2/contrib/openshift/base-plugins.txt

pulling in recent fixes we've targeted for 3.7
going to let an overnight test run or two go green prior to requesting plugin / image update for rhel

bump sync to 0.1.32

---

2/contrib/s2i/run

The Jenkins monitoring plugin stores its data in /var/lib/jenkins/monitoring/<hostName>.
Since the pod name changes everytime there is a deployment, any trending data is lost over
re-deployments. We force the application name to allow for historical data collection.

Improve support for Jenkins monitoring plugin

---

2/contrib/jenkins/kube-slave-common.sh

a RHEL7 image was added in https://github.com/openshift/jenkins/pull/371.
This is adding a CentOS7 image.
The referenced CentOS image is available on registry.centos.org.
The Dockerfile is in the [dotnet-jenkins-slave](https://github.com/redhat-developer/dotnet-jenkins-slave) repo.
Implements https://github.com/redhat-developer/dotnet-jenkins-slave/issues/3
@bparees PTAL
CC @jerboaa @omajid @aslicerh

Add .NET Core 2.0 CentOS slave

---

2/contrib/s2i/run
slave-base/contrib/bin/run-jnlp-client

- Set CONTAINER_INITIAL_PERCENT to something small by
default, rather than 100%. Setting it to 100% results in `-Xms==-Xmx`
which is bad as it tells the GC that it's fine to use at least the max amount.
Thus it'll never attempt to return pages to the OS which it would otherwise do when
`-Xms` is set to something small. That's memory other containers could use.
- Use `-Dsun.zip.disableMemoryMapping=true` as this saves some percent
on memory. The added (performance) cost for class loading is negligible.
- Set `-XX:MinHeapFreeRatio` and `-XX:MaxHeapFreeRatio` to more aggressive values. This together with a low -Xms will make the GC do the right thing.
- Set `-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap` unconditionally
as this tells the JVM that physical memory is …

Fix OpenJDK default settings so as to use less memory.

---

2/contrib/jenkins/install-plugins.sh

The default timeout of 5 seconds for downloading plugins are to narrow for us.
This PR increases the curl connection timeout from 5 to 20 seconds. This follows the original [install-plugins-sh](https://github.com/jenkinsci/docker/commit/21b0f37a8b2d4dfa359cfa87eb849531ff5a9290) from the [official jenkins docker image](https://github.com/jenkinsci/docker)
At the same time make it possible to configure the timeouts for plugin downloads, which also reflects the script from the original jenkins docker image. See [install-plugins.sh#L78](https://github.com/jenkinsci/docker/blob/master/install-plugins.sh#L78)

Make plugin download timeouts configurable

---

2/contrib/openshift/base-plugins.txt

this will facilitate both bug verification and upcoming card work (i.e. writing extended tests for the secret<->credential mapping that has dropped)
note: I'll wait on the rhel rpm update until the 3.7 refresh is finished

pull in post 3.7 GA plugin changes

---

2/Dockerfile
slave-base/Dockerfile

note that i'm intentionally not doing this for the rhel images.  it would require changes to our CI jobs that aren't worth doing since the rhel-built images produced from this repo aren't what we ship anyway.
fixes https://github.com/openshift/jenkins/issues/456

use v3.7 release tagged base image

---

2/contrib/openshift/base-plugins.txt

When using `withCredentials` with v1.12 of the credentials-binding
plugin causes the console output to become corrupted with extra
asterisks making output difficult to read.  This is also described in [JENKINS-41760](https://issues.jenkins-ci.org/browse/JENKINS-41760)

Update credentials-binding plugin

---

2/contrib/openshift/base-plugins.txt

The changelog for this plugin can be seen here:
https://plugins.jenkins.io/script-security
The following advisory was addressed in version 1.37:
https://jenkins.io/security/advisory/2017-12-11/

🔒 Update to latest script-security for advisory

---

2/contrib/s2i/run

Added a new variable so it's possible to pass additional Java options to Jenkins, like those [useful for the Kubernetes plugin](https://github.com/jenkinsci/kubernetes-plugin#over-provisioning-flags) without disturbing or redefining other Java flags.

add variable for additional Java user options

---

2/Dockerfile
2/Dockerfile.rhel7

Fixes https://github.com/openshift/jenkins/issues/421
Fixes https://github.com/openshift/release/issues/432
did not find any yum repos for either centos or rhel
use of entrypoint/cmd combo was per tini doc recommendations ... does that interfere with our s2i extension path ?
putting all of it in CMD directive did not work

employ dumb-init as init process, handle docker zombies

---

2/contrib/openshift/base-plugins.txt

@openshift/sig-developer-experience @stevekuznetsov fyi
this pulls in the fix for @stevekuznetsov 's issue using tokens without logging in via the browser after restarting jenkins pods with pv's; it also pulls in a fix for another possible issue when the clock is not set

bump login plugin for token first usage timing bug after restart on PV

---

2/contrib/openshift/base-plugins.txt

for https://bugzilla.redhat.com/show_bug.cgi?id=1533938
@bparees @jupierce @adammhaile fyi - will propose to support / customer that this will go out with the next errata; hopefully that is sufficient, along with downloading the plugin from the jenkins update center, vs. a hot fix

bump login plugin for bearer token after restart fix

---

README.md

Fixes https://github.com/openshift/jenkins/issues/477

add clarification around oc version and image tags

---

2/contrib/openshift/base-plugins.txt

Fixes https://github.com/openshift/jenkins/issues/428
in addition to bumping blue ocean, it removes plugin versions from our security advisory list that are now getting pulled by the pipeline/workflow plugin aggregator
also, moving the pipeline / workflow aggregator to the end helped with bumping the version of security advisory plugins if those plugins were optional plugins for pipeline / workflow

bump blueocean; clean up stale security adv bumps

---

2/contrib/openshift/base-plugins.txt

also declaring this the `1.0.0` version .... no new changes planned for 3.9
and making the `0.` to `1.` transition for typical PR, statement of confidence type reasons

bump sync plugin for blueocean related updates

---

2/Dockerfile.rhel7
2/contrib/jenkins/install-plugins.sh
2/contrib/s2i/run
2/test/s2i/configuration/config.xml
Makefile

@jupierce @adammhaile @bparees for recent brew failures
in addition to the raw noarch change, I pulled in migration fixes we had to drop in 3.7 after initially releasing with just the raw noarch change

pull in 3.7 9b5f7bf 7ef705b 9db8ae2

---

2/contrib/openshift/base-plugins.txt

@openshift/sig-developer-experience 
per pr description, to pull in recent sync plugin fix for proper order of stages in build annotation leveraged by openshift UI (adjustment on a fix made this release cycle for handling some of the new features introduced with declarative pipeline syntax and blueocean that are not available with the base pipeline support used historically)

bump sync version for stage ordering fix

---

2/contrib/openshift/base-plugins.txt

for recent client and sync plugin fixes
note, client went from 1.0.5 to 1.0.7 cause 1.0.6 introduced a regression with non default clusters

bump sync and client plugins for recent fixes

---

2/Dockerfile
2/contrib/openshift/base-plugins.txt

Fixes https://github.com/openshift/jenkins/issues/509
@openshift/sig-developer-experience fyi / ptal
I've built an image from this locally and ran our 'openshift pipeline builds' extended test suite with success against that image.
Also, the dist-git updates to update the jenkins rpm used to build our rhel images has already occurred, with the associated jobs/artifacts noted in the above issue.

update core/plugin versions for recent jenkins security advisories

---

2/contrib/openshift/configuration/init.groovy.d/init.groovy
pkg/jenkins/jenkins.go

I've observed within the last few weeks and inordinate delay the very first time you login to a jenkins instance instantiated from our image, often resulting in a 504 / gateway timeout
In conjunction, I observer a lengthy CPU burn with the jenkins process.  And it occurred across different permutations (i.e. both with oauth on and off, no openshift pod, etc.)
Thread dumps during the CPU burn revealed that the administrative alerts were being accessed on the login threads, and the jenkins core update / security alert monitors were taking forever, downloading/parsing their json data.  
UPDATE March 5 2018:
Instead of the monitor disablement below, we were able to move the processing to jenkins startup via an init groovy scrip
END UPDATE
I suspect a …

perform update center syncrhonization during startup instead of first login

---

2/Dockerfile

for the rhel side, I ran https://buildvm.openshift.eng.bos.redhat.com:8443/job/devex/job/devex%252Fjenkins-bump-version/12/

bump to lts 2.107.1 announced this week

---

2/contrib/openshift/configuration/init.groovy.d/update-center-init.groovy

moving these downloads to a separate threads will accelerate jenkins startup to some degree, if sufficient cpu/cores are available, though my testing shows the pod may still not be deemed ready until the download completes, based on whether the readiness probes can squeeze out enough cpu even after the jenkins is up and ready message appears

move update center init groovy to background thread

---

2/contrib/jenkins/kube-slave-common.sh

fixes https://bugzilla.redhat.com/show_bug.cgi?id=1548619
@bparees this will actually strip the gorp preceding the -----BEGIN CERTFICATE ------ line 
@bostrt fyi ... with the discussion in the bugzilla, the last change in flight got list and merged before I could update

use openssl to strip bag attributes as well

---

2/Dockerfile
2/contrib/openshift/base-plugins.txt

I'm going to hold this a tad until sorting out the heap / startup contention issue with out extended tests

go back to v2.107; bump login plugin to v1.0.7 to tolerate v2.107

---

2/Dockerfile
2/contrib/openshift/base-plugins.txt
README.md

Changelog: https://jenkins.io/changelog-stable/#v2.107.2
Mailer plugin shows up as an admin warning because of
https://jenkins.io/security/advisory/2018-03-26/#SECURITY-774
I'm not sure what pulls in the mailer plugin, but I just added it here
in the same way as others appear to have been added.
----
When I build this VM locally now, I get the following 3 admin warnings:
Let me know if there are any of those that you'd like me to fix here also!

Upgrade Jenkins to 2.107.2; mailer plugin to 1.21

---

agent-nodejs-8/Dockerfile
agent-nodejs-8/Dockerfile.rhel7

It is not possible to test node 8 applications that depend on NPM modules with native extensions. Adding `make` and `gcc-c++` fixes this.
E.g. currently if you run `npm install scrypt` in the `openshift/jenkins-agent-nodejs-8-centos7` container you will receive the following exception:
```shell
$ npm install scrypt
> scrypt@6.0.3 preinstall /var/lib/origin/node_modules/scrypt
> node node-scrypt-preinstall.js
Error: Error: Command failed: ./configure
configure: error: in `/var/lib/origin/node_modules/scrypt/scrypt/scrypt-1.2.0':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details
> scrypt@6.0.3 install /var/lib/origin/node_modules/scrypt
> node-gyp rebuild
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at …
```

Add support for NPM modules with native extensions

---

2/contrib/s2i/run

The single quotes around the value were causing a plugin init fail:
Caused by: java.lang.IllegalArgumentException: Unknown counter: 'log
at net.bull.javamelody.FilterContext.setDisplayedCounters(FilterContext.java:237)
at net.bull.javamelody.FilterContext.initCounters(FilterContext.java:196)

Fix the value of -Djavamelody.displayed-counters

---

agent-maven-3.5/contrib/bin/configure-agent
slave-base/contrib/bin/run-jnlp-client
slave-maven/contrib/bin/configure-slave

the run-jnlp-client script in slave base tries to enable the javac alternative, but there's no JDK installed (only a JRE) so it fails:
```
$ docker run -it brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/openshift3/jenkins-agent-nodejs-8-rhel7 /bin/sh
alternatives version 1.7.4 - Copyright (C) 2001 Red Hat, Inc.
This may be freely redistributed under the terms of the GNU Public License.
usage: alternatives --install <link> <name> <path> <priority>
[--initscript <service>]
[--family <family>]
[--slave <link> <name> <path>]*
alternatives --remove <name> <path>
alternatives --auto <name>
alternatives --config <name>
alternatives --display <name>
alternatives --set <name> <path>
alternatives --list
common options: --verbose --test --help --usage --version --keep-missing
--altdir …
```

don't configure javac in base slave image

---

README.md
slave-base/contrib/bin/run-jnlp-client

cherry-picked master fix to create 3.6 version fix for https://bugzilla.redhat.com/show_bug.cgi?id=1573648
Have tested against 3.6 cluster using the current k8s plugin we ship there, namely v0.10

default jenkins master, jnlp tunnel, to no_proxy list

---

agent-nodejs-8/README.md
agent-nodejs-8/contrib/bin/configure-agent

As mentioned https://github.com/openshift/jenkins/pull/545#issuecomment-389445502, I split it in favour of 2 distinct PR.
This enable a similar customization as maven agent but for node registry instead of maven repository.

add NPM_MIRROR_URL support to use a node mirror registry

---

2/contrib/jenkins/install-plugins.sh
2/contrib/s2i/assemble
2/contrib/s2i/save-artifacts

I was trying to keep the changes to a minimum to avoid a big divergence from the upstream `install-plugins.sh`. However, that means the change is not as clean as it could be. Let me know what you think - I could refactor the `download` and `doDownload` functions a bit more to avoid duplication at the cost of diverging from the upstream.
I've tested this with our image, which installs about 80 plugins, and the (incremental) build time got from 200s to about 35s.

Add save-artifacts s2i script for incremental builds

---

slave-base/contrib/bin/run-jnlp-client

As of version 1.6.0 of the Jenkins Kubernetes plugin,
args are no longer passed to jnlp container if not present in containerTemplate
See https://github.com/jenkinsci/kubernetes-plugin/pull/315
This is made worse if using Declarative pipeline and specifying yaml for the podTemplate.
since ${computer.*} is not resolvable.
To workaround this, we use JENKINS_SECRET and JENKINS_NAME for launcher arguments
See https://gist.github.com/scoheb/f29d263c240e8880648b920240635ed6 for an example Jenkinsfile

Amend arguments if none passed to run-jnlp-client

---

2/Dockerfile
agent-maven-3.5/Dockerfile
slave-base/Dockerfile
slave-maven/Dockerfile

See recent test failures in https://github.com/openshift/jenkins/pull/623
@openshift/sig-developer-experience @openshift/sig-continuous-delivery @grdryn fyi

similar to rhel, bypass on centos of rpm -V on java rpms

---

2/contrib/openshift/base-plugins.txt

Advisory: https://jenkins.io/security/advisory/2018-06-04/
kubernetes 1.6.2 -> 1.7.1
https://github.com/jenkinsci/kubernetes-plugin/blob/master/CHANGELOG.md
git 3.8.0 -> 3.9.1
https://plugins.jenkins.io/git
github 1.26.0 -> 1.29.1
https://plugins.jenkins.io/github
github-branch-source 2.2.3 -> 2.3.6
https://plugins.jenkins.io/github-branch-source

🔒 Upgrade plugins for Jenkins advisory 2018-06-04

---

2/contrib/openshift/base-plugins.txt

also, still sorting out with @openshift/sig-continuous-delivery and/or @openshift/sig-continuous-infrastructure on who owns the plumbing behind https://buildvm.openshift.eng.bos.redhat.com:8443/job/devex/job/devex%252Fjenkins-plugins/ after the recent reorg and whether we can generate plugin rpms for 3.11

bump sync/client plugins for recent fixes

---

2/contrib/jenkins/kube-slave-common.sh

Due to the nature of Jenkins, I have found the container cap to be quite low. Even for new consumers testing the OpenShift Jenkins, I believe will hit this cap very quickly which turns into a poor user experience. IMHO.

bump container cap to 100

---

2/contrib/openshift/base-plugins.txt

note, the sync plugin jump from 20 to 23 was not a mistake ... just managed to cut new versions of the sync plugin for fixes before I cut a new jenkins image with the updated versions

bump client, sync plugin versions for recent changes

---

2/Dockerfile

https://jenkins.io/security/advisory/2018-07-18/

⬆ Upgrade Jenkins to latest LTS 2.121.2

---

2/Dockerfile.rhel7
2/contrib/s2i/run
agent-maven-3.5/Dockerfile.rhel7
slave-base/contrib/bin/run-jnlp-client
slave-maven/Dockerfile.rhel7

Dockerfile changes needed to build ppc64le + x86 containers from same Dockerfile.
Adding  java/javac to 'alternatives' logic so ppc64le (and other archs) can successfully start jenkins.

Dockerfile edits and set java path for multiarch builds 

---

2/contrib/jenkins/install-plugins.sh

if your plugins.txt is empty, then *.lock will not be created and your code in line 433 crashed with 
``rm: cannot remove ‘/opt/openshift/plugins/*.lock’: No such file or directory``
is not good for me 😉

suggestion

---

2/contrib/s2i/run

I think https://github.com/openshift/jenkins/pull/749 grabbed a cached 2-centos build vs. building one with 2.138.4
/hold

fix spacing / make sure new lts worked

---

2/contrib/openshift/base-plugins.txt

From https://jenkins.io/security/advisory/2019-01-08/#SECURITY-1266:
```
SECURITY-1266 / CVE pending
Script Security sandbox protection could be circumvented during the
script compilation phase by applying AST transforming annotations such
as @Grab to source code elements.
Both the pipeline validation REST APIs and actual script/pipeline
execution are affected.
This allowed users with Overall/Read permission, or able to control
Jenkinsfile or sandboxed Pipeline shared library contents in SCM, to
bypass the sandbox protection and execute arbitrary code on the
Jenkins master.
All known unsafe AST transformations in Groovy are now prohibited in
sandboxed scripts.
```
On the Update page in the Plugin Manager inside Jenkins, for the
"Pipeline: Declarative" (pipeline-model-definition), there's …

🔒 Upgrade plugin versions for security-1266

---

2/contrib/openshift/base-plugins.txt

as you noted elsewhere, with our forcing the jenkins imagestream to what is on docker.io in the openshift/origin e2e and no longer tagging in the newly built image with our special openshift/release template, we won't test this change until after this merges (other than my local testing)

bump login plugin for correct api version for self-sar on 4.0

---

2/Dockerfile

This PR bumps Jenkins core version to the latest LTS release.
Fixes #770

update Jenkins to 2.150.2 LTS

---

2/contrib/openshift/base-plugins.txt

https://jenkins.io/security/advisory/2018-09-25/
Note: the 2019 sec advisories bumped config-file-provider to 3.5 so we did not pull the 3.2 bump from https://github.com/openshift/jenkins/pull/709

🔒 Upgrade plugins for Jenkins advisory 2018-09-25

---

2/contrib/jenkins/install-jenkins-core-plugins.sh

We never upgraded to 2.164.1 because there were no security fixes, but
now 2.164.2. See the changelog for all changes:
https://jenkins.io/changelog-stable/

🔒 Upgrade to latest LTS 2.164.2

---

2/contrib/s2i/run
2/test/jenkins_test.go
agent-maven-3.5/test/agent_maven_test.go
slave-base/Dockerfile.localdev

/assign @waveywaves 
step one in getting the old docker socket based unt/cmd line tests back into PR verification
these tests had been out of the loop for long enough they needed some cleanup
both openshift/aos-cd-jobs and  openshift/release PR will follow once this merges

various clean up to get 'make test' functional again for PR testing

---

2/Dockerfile
2/Dockerfile.rhel7
slave-base/Dockerfile
slave-base/Dockerfile.rhel7

The current slave-base image for v3.11 uses an alpha version of the oc cli:
```
$ docker pull openshift/jenkins-slave-base-centos7:v3.11
v3.11: Pulling from openshift/jenkins-slave-base-centos7
Digest: sha256:9aecbcc01b854c1050117dd567645faea2e1aa06697d5e5108519981883f0993
Status: Downloaded newer image for openshift/jenkins-slave-base-centos7:v3.11
$ docker run -ti openshift/jenkins-slave-base-centos7:v3.11 /bin/bash
bash-4.2# oc version
oc v3.11.0-alpha.0+1ff2229-9
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO
``` 
Besides being an alpha version, it also does not have some features available in the released version, like `oc wait`.
This PR changes the base image to use quay.io since the image from docker hub is deprecated since 3.10.

use non-alpha version of oc cli on 3.11 slave-base

---

2/contrib/openshift/base-plugins.txt

Bug 1732346: (CVE-2019-1010241) - CVE-2019-1010241 jenkins-plugin-credentials-binding: storing passwords in recoverable format leading to authenticated users being able to recover credentials

Bug NEED CLONE 1732346: Bump Credentials Binding Plugin to v1.19

---

2/Dockerfile.rhel7
agent-maven-3.5/Dockerfile.rhel7
agent-nodejs-8/Dockerfile.rhel7
slave-base/Dockerfile.rhel7

let's see what breaks. In theory nothing should since yum-config-manager
is no-op'ing anyway.
OSBS strips these yum-config-manager invocations and on the origin/CI side of the house, they are being no-op'd, so they should have no effect there either.

remove all yum-config-manager invocations from Dockerfiles

---

2/contrib/openshift/base-plugins.txt

This PR fixes the following CVE
https://jenkins.io/security/advisory/2019-07-31/

Bug 1735527: 3.11 cve 2019 10357 bump workflow cps global lib version to 2.15

---

2/contrib/openshift/base-plugins.txt

Updates: 
Wrt the fix in https://github.com/openshift/jenkins-client-plugin/pull/287 workflow-cps plugin versions above 2.71 are now usable as they do not give the warning it used to before which was due to a bug in the jenkins client plugin itself which was also solved in the PR above.
Plugins updating:
workflow-cps FROM 2.65 -> 2.73
jenkins-client-plugin FROM 2.65 -> 2.73

Bump plugin versions wrt workflow-cps fix in client plugin

---

2/contrib/openshift/base-plugins.txt

Bumps the version of the openshift-login-plugin to 1.0.20 which bring fixes and enhancement to OCP 4.1 and 4.2.

Bump openshift-jenkins-login-plugin to version 1.0.20

---

2/contrib/openshift/base-plugins.txt
openshift/templates/jenkins-ephemeral-monitored.json
openshift/templates/jenkins-persistent-monitored.json

_Enable users to tract the resource utilization by Jenkins by integrating with Openshift Monitoring._
https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/getting-started.md#related-resources
https://github.com/coreos/prometheus-operator/blob/master/Documentation/troubleshooting.md#overview-of-servicemonitor-tagging-and-related-elements
cc @akram @gabemontero

Prometheus Monitoring Integration

---

README.md
hack/build.sh

This is required to allow: 
- build with RHEL8 (which has not docker anymore)
- build multistage to get rid of dumb-init

Allow use of podman or buildah by using the BUILD_COMMAND variable

---

2/contrib/openshift/base-plugins.txt

Fixes CVE cve-2019-10432 : updates script-security-plugin to 1.66 and htmpublisher-plugin to 1.21

Bug 1764464: cve-2019-10432: Stored xss vulnerability

---

2/Dockerfile.localdev
2/Dockerfile.rhel7
2/contrib/jenkins/install-jenkins-core-plugins.sh

Bumps Jenkins version to 2.176.4 to fix various CVE flaws

Bug 1764481: Bump jenkins version to 2.176.4 : cve-2019-10401..10406

---

2/contrib/openshift/configuration/jenkins.model.JenkinsLocationConfiguration.xml.tpl
2/contrib/s2i/run

fixes #969 
Forcibely set JENKINS_URL and reflects JENKINS_SERVICE_NAME and its route
- Creates jenkins.model.JenkinsLocationConfiguration.xml
- Set JENKINS_URL to match the first route service service JENKINS_SERVICE_NAME

Forcibely set JENKINS_URL and reflects JENKINS_SERVICE_NAME 

---

2/contrib/openshift/base-plugins.txt

This is a fake fix to allo the tracker for  bz-1764460 to be updated

Bug 1764460: Re-ordering some plugins in alphabetical order

---

2/contrib/openshift/configuration/logging.properties
2/contrib/s2i/run

Format logs in the console to be more readable
example
```
2019-10-29 15:34:19 INFO     jenkins.InitReactorRunner$1 onAttained Augmented all extensions
2019-10-29 15:34:19 INFO     jenkins.InitReactorRunner$1 onAttained Loaded all jobs
```

Format logs

---

2/Dockerfile.localdev
2/Dockerfile.rhel7
2/contrib/s2i/run

This is temporary as we are waiting for tls 1.3 support to be fixed in openjdk 11

Add java-1.8.0 and set it as default while openjdk 11 bug with tls 

---

2/Dockerfile.localdev

Disable rhel-fast-datapath-beta repo as it has silently be added to origin-cli image

Disable rhel-fast-datapath-beta repo

---

agent-nodejs-10/Dockerfile.rhel7

- This updates the nodejs-10 agent image Docker file to have correct labels for the Openshift 4.4 release.

Update nodejs-10 agent image with correct labels

---

2/Dockerfile
2/Dockerfile.localdev
2/Dockerfile.rhel7
2/contrib/jenkins/jenkins-common.sh
2/contrib/s2i/run
HACKING.md
agent-maven-3.5/Dockerfile
agent-maven-3.5/Dockerfile.localdev
agent-maven-3.5/Dockerfile.rhel7
agent-nodejs-10/Dockerfile
agent-nodejs-8/Dockerfile
slave-base/Dockerfile
slave-base/Dockerfile.localdev
slave-base/Dockerfile.rhel7
slave-base/contrib/bin/generate_container_user
slave-base/contrib/bin/run-jnlp-client

cri-o automatically appends the arbitrary user assigned by openshift to /etc/passwd.
/etc/passwd doesn't have to be group writable then, neither we need nss_wrapper.
This PR removes the use of both for 4.2+

Bug 1793323: Remove the use of  /etc/passwd in favor of cri-o

---

2/contrib/openshift/base-plugins.txt

`openshift-login` plugin has been updated to 1.0.23 which contians fix for Bugzilla 1810429

Bug 1810429: Bump login plugin to 1.0.23

---

2/Dockerfile
2/Dockerfile.localdev
2/contrib/jenkins/install-jenkins-core-plugins.sh
2/contrib/openshift/base-plugins.txt
2/contrib/s2i/run
2/go-init/Dockerfile
2/go-init/LICENSE
2/go-init/README.md
2/go-init/main.go
agent-maven-3.5/Dockerfile.localdev
agent-maven-3.5/Dockerfile.rhel7
slave-base/Dockerfile.localdev
slave-base/Dockerfile.rhel7
slave-base/go-init/Dockerfile
slave-base/go-init/LICENSE
slave-base/go-init/README.md
slave-base/go-init/main.go

This is a catch-up PR as we decided to keep 4.1 because of deprecation.
It adds:
- use of go-init instead of dumb-init that is not resolvable in epel
- use of Jenkins 2.204.2
- use of latest plugins

Bug 1810393: 4.1  2.204.2 and plugins updates

---

OWNERS

Add jkhelil as approver and reviewer

---

agent-nodejs-12/Dockerfile
agent-nodejs-12/Dockerfile.localdev
agent-nodejs-12/Dockerfile.rhel7
agent-nodejs-12/README.md
agent-nodejs-12/cccp.yml
agent-nodejs-12/contrib/bin/configure-agent
agent-nodejs-12/contrib/bin/scl_enable
agent-nodejs-12/test/agent_nodejs_test.go

- Add Support for Nodejs 12 Agent for Jenkins

Support Nodejs 12 Agent

---

openshift/templates/jenkins-ephemeral-monitored.json
openshift/templates/jenkins-persistent-monitored.json

To create the Service Monitor custom resource in the Templates,
provided by the Prometheus Operator in Openshift,
users needs specific RBAC permissions to be able to create them.
This necessity needs to be understood by them, hence adding this to the
description of the templates.

Bug 1820677: Update Description on Monitored Templates reflecting permission issues

---

agent-maven-3.5/contrib/bin/configure-agent

The script errors silently, because we are using a sed delimiter that is already present in the no_proxy value
Wondering if may we need set -euxo pipefail on these scripts but i dont want to wake up dameons 
sed -i 's|| <proxy>         <id>genhttpproxy</id>         <active>true</active>         <protocol>http</protocol>         <host>*****</host>         <port>3128</port>      <username>*****</username>      <password>***</password>       <nonProxyHosts>*.cluster.local,*.svc|.us-east-2.compute.internal|10.0.0.0/16|10.128.0.0/14|127.0.0.1|169.254.169.254|172.30.0.0/16|api-int.xiuwang-py2.qe.devcluster.openshift.com|etcd-0.xiuwang-py2.qe.devcluster.openshift.com|etcd-1.xiuwang-py2.qe.devcluster.openshift.com|etcd-2.xiuwang-py2.qe.devcluster.openshift.com|localhost|test.no-proxy.com</nonProxy …

Bug 1813217: fix maven proxy settings

---

2/Dockerfile.localdev
slave-base/Dockerfile.localdev

This image contains a version of oc run that still creates
deploymentconfig and this is required by our e2e tests

Bug 1849094: Use quay.io/openshift/origin-cli:4.2 as base image for upstream

---

2/contrib/openshift/base-plugins.txt

jenkins-credentials-binding-plugin 1.0.23 : improper masking of secrets

Bug 1848215: CVE-2020-2182: jenkins-credentials-binding-plugin 1.0.23

---

2/Dockerfile.rhel8
agent-maven-3.5/Dockerfile.rhel8
agent-nodejs-10/Dockerfile.rhel8
agent-nodejs-12/Dockerfile.rhel8
slave-base/Dockerfile.rhel8

Separate files are required, as the changes necessary for building with
RHEL 8 content are not compatible with RHEL 7.  agent-nodejs-8 is skipped,
as RHEL 8 never shipped it.

Add Dockerfile.rhel8 throughout

---

agent-maven-3.5/Dockerfile.rhel7

This rpm -e command was added to make rh-maven35 package installable as it requires
java1.8, but then we delete java 1.8 and maven can run with openjdk-11.
With the revert and opt-in strategy for maven35 and openjdk we reverted this one only partially.

Bug 1848611: Remove execution of rpm -e java-1.8.0.

---

2/contrib/openshift/base-plugins.txt

Various CVE including CVE-2020-2135 CVE-2020-2136: Update subversion plugin to 2.13.1

[release-4.3] Bug 1819530: update subversion plugin

---

openshift/imagestreams/jenkins-agent-nodejs-rhel.json
openshift/imagestreams/jenkins-agent-nodejs-rhel.yaml

Reference location for image : https://catalog.redhat.com/software/containers/openshift4/jenkins-agent-nodejs-12-rhel7/5ea81a4ad70cc54b02d62294?container-tabs=gti

Bug 1883836: Update nodejs-agent imagestream to v12

---

slave-base/Dockerfile.rhel8

Updating ose-jenkins-agent-base builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/ose-jenkins-agent-base.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
Depends on https://github.com/openshift/oc/pull/606 . Allow it to merge and then run `/test all` on this PR.

Updating ose-jenkins-agent-base builder & base images to be consistent with ART

---

agent-maven-3.5/Dockerfile.rhel8

Updating ose-jenkins-agent-maven builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/ose-jenkins-agent-maven.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
Depends on https://github.com/openshift/jenkins/pull/1165 . Allow it to merge and then run `/test all` on this PR.

Updating ose-jenkins-agent-maven builder & base images to be consistent with ART

---

agent-nodejs-12/Dockerfile.rhel8

Updating ose-jenkins-agent-nodejs-12 builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/ose-jenkins-agent-nodejs-12.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
Depends on https://github.com/openshift/jenkins/pull/1165 . Allow it to merge and then run `/test all` on this PR.

Updating ose-jenkins-agent-nodejs-12 builder & base images to be consistent with ART

---

agent-nodejs-10/Dockerfile.rhel8

Updating ose-jenkins-agent-nodejs-10 builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/ose-jenkins-agent-nodejs-10.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
Depends on https://github.com/openshift/jenkins/pull/1165 . Allow it to merge and then run `/test all` on this PR.

Updating ose-jenkins-agent-nodejs-10 builder & base images to be consistent with ART

---

2/contrib/openshift/base-plugins.txt

Fix already exists in https://github.com/apache/ant/commit/87ac51d3c22bcf7cfd0dc07cb0bd04a496e0d428
Using latest release of ant plugin as it is using the fixed version of ant

[main] Bug 1904307: Update ant plugin CVE-2020-11979

---

2/Dockerfile.rhel8
slave-base/Dockerfile.rhel8

Bug 1950175: Build with Go 1.16

---

agent-maven-3.5/Dockerfile.localdev

[head] Bug 1929052: Add missing backslash to agent maven dockerfile

---

2/contrib/openshift/base-plugins.txt

Remove hard dependency on kubernetes-client-api to allow automatic resolution.
This is needed by the sync plugin which may require higher version than the kubernetes-plugin.

Remove hard dependency on kubernetes-client-api

---

2/contrib/jenkins/kube-slave-common.sh
2/contrib/openshift/configuration/credentials.xml.tpl
2/contrib/s2i/run

This is no longer necessary in recent versions of the plugin and it
causes problems because if a user is using configuration-as-code to
define their own credentials, it will overwrite our changes and the
kubernetes plugin will get confused trying to use it.
See: https://bugzilla.redhat.com/show_bug.cgi?id=1956652
See: https://access.redhat.com/solutions/6016001

Nuke custom credentials for kubernetes-plugin

---

2/contrib/s2i/run

This is normally enforced by Jenkins itself, though since this is injected through direct modification of the XML file, the incorrect version stays in. There are rare situations when plugins do not expect the values does not adhere to invariants imposed by Jenkins and fail when run in OpenShift:
https://github.com/jenkinsci/jenkins/blob/a1175b932e1ac97085d69752f5821141d012314f/core/src/main/java/jenkins/model/JenkinsLocationConfiguration.java#L144

Bug 1972451: Correctly declare Jenkins URL with trailing slash

---

2/contrib/s2i/run
agent-maven-3.5/contrib/bin/configure-agent
slave-base/contrib/bin/run-jnlp-client

In code there are embedded paths that are valid only for cgroups v1. This PR creates functions that calculate memory in container either for v1 or v2 of cgroups.

Bug 1971537: Support cgroups v2

---

smoke/features/jenkins-maven-agent.feature
smoke/features/jenkins-nodejs-agent.feature
smoke/features/jenkins-teardown-ephemeral.feature
smoke/features/persistent-jenkins.feature
smoke/features/persistent-maven-agent.feature
smoke/features/persistent-nodejs-agent.feature
smoke/features/steps/openshift.py
smoke/features/steps/plugins.py
smoke/features/steps/steps.py

- Adding test for persistent template
- Adding scenario to tear down the test project for all resources created while testing the ephemeral template
- Adding maven agent test for persistent template
- Adding nodejs agent test for persistent template

adding persistent template test and updating some

---

2/contrib/openshift/base-plugins.txt

In preparation to release openshift-sync plugin 1.0.46

Bug 1925524: bump k8s plugin to 1.30 to enable 1.0.48 release of openshift sync plugin

---

2/Dockerfile.localdev
2/Dockerfile.rhel7
2/Dockerfile.rhel8
2/contrib/jenkins/install-jenkins-core-plugins.sh

This PR updates broken Jenkins image in 4.7 and 4.8 which introduced a faulty dependant plugin.
The updated plugin needs this version of Jenkins.

Bug 1972354: Bump jenkins version 2.289.2

---

smoke/features/README.md
smoke/features/steps/openshift.py
smoke/features/steps/project.py
smoke/features/steps/steps.py
smoke/features/stress-test.feature

**Testing the performance of sync plugin**
```
- create 5 builds
- bring down jenkins
- delete a few of the builds via oc
- bring jenkins back up
- see that sync plugin is able to reconcile state and delete the job runs associated with the builds we deleted
```
- Update the README.MD for smoke test

Bug 1993195: testing performance of sync plugin

---

2/contrib/openshift/base-plugins.txt

In order to fix the `CVE-2021-21684`, git plugin version has to be updated to version `4.8.3` according to [Jenkins Security Advisory 2021-10-06](https://www.jenkins.io/security/advisory/2021-10-06/)

Bug 2015085: update git plugin to version 4.8.3

---

2/Dockerfile.localdev
2/Dockerfile.rhel7
2/Dockerfile.rhel8
2/contrib/jenkins/install-jenkins-core-plugins.sh

In order to fix `CVE-2014-3577` and a bunch of other security issues, jenkins version is bumped to a current LTS, `2.303.3`.

Bug 2020616: update jenkins version to 2.303.3 (security update)

---

2/contrib/openshift/base-plugins.txt

Subversion plugin version is updated to 2.15.1 in order to fix security issues (see more at https://www.jenkins.io/security/advisory/2021-11-04/#fix).

Bug 2020610: Update subversion plugin to 2.15.1

---

2/contrib/s2i/run

Rather than picking the first route then checking if it matches, select from *all routes* then grab the host of the matching one.

Fixes #1241

---

2/Dockerfile.localdev
2/Dockerfile.rhel7
2/Dockerfile.rhel8
2/contrib/jenkins/install-jenkins-core-plugins.sh
2/contrib/openshift/base-plugins.txt

- Update Jenkins core to 2.303.3 to address critical CVE adivsories
- Update Subversion plugin to 2.15.1 to address CVE-2021-21698

[release-4.9] Bug 2020615: Update Jenkins and plugins per 2021-11 advisory

---

2/Dockerfile.localdev
2/Dockerfile.rhel7
2/Dockerfile.rhel8
2/contrib/jenkins/install-jenkins-core-plugins.sh
2/contrib/openshift/base-plugins.txt

- Update Jenkins core to 2.303.3 to address critical CVE adivsories
- Update Subversion plugin to 2.15.1 to address CVE-2021-21698

[release-4.6] Bug 2020612: Update Jenkins and plugins per 2021-11 advisory

---

2/Dockerfile.localdev
2/Dockerfile.rhel7
2/Dockerfile.rhel8
2/contrib/jenkins/install-jenkins-core-plugins.sh
2/contrib/openshift/base-plugins.txt

- Update Jenkins core to 2.303.3 to address critical CVE adivsories
- Update Subversion plugin to 2.15.1 to address CVE-2021-21698

[release-4.7] Bug 2020613: Update Jenkins and plugins per 2021-11 advisory

---

2/Dockerfile.localdev
2/Dockerfile.rhel7
2/Dockerfile.rhel8
2/contrib/jenkins/install-jenkins-core-plugins.sh
2/contrib/openshift/base-plugins.txt

- Update Jenkins core to 2.303.3 to address critical CVE adivsories
- Update Subversion plugin to 2.15.1 to address CVE-2021-21698

[release-4.8] Bug 2020614: Update Jenkins and plugins per 2021-11 advisory

---

2/Dockerfile
2/contrib/openshift/base-plugins.txt

Bump Jenkins to 2.303.3 to address multiple security fixes in the 2021-11 advisory:
- CVE-2021-21685
- CVE-2021-21686
- CVE-2021-21687
- CVE-2021-21688
- CVE-2021-21689
- CVE-2021-21690
- CVE-2021-21691
- CVE-2021-21692
- CVE-2021-21693
- CVE-2021-21694
- CVE-2021-21695
- CVE-2021-21696
- CVE-2021-21697
Also includes the following plugin updates:
- Update Subversion plugin to 2.215.1 to address CVE-2021-21698.
- Updates to resolve transitive dependencies in other plugins:
- mailer - update to 1.34
- parameterized-trigger - update to 2.39
- workflow-cps - update to 2.90
- Add pipeline-* plugins 
- Add workflow-* plugins

[release-3.11] Bug 2020611: Update Jenkins and plugins per 2021-11 advisory

---

scripts/test-jenkins-template-install.sh
smoke/features/jenkins-maven-agent.feature
smoke/features/jenkins-nodejs-agent.feature
smoke/features/jenkins-teardown-ephemeral.feature
smoke/features/persistent-maven-agent.feature
smoke/features/steps/steps.py

Changing the smoke test so they can be run in openshift-ci i.e in an environment where creating new namespaces is not allowed
* Adding detection of OPENSHIFT_CI env var and in this case run the smoke tests in the current namespace
* Adds resources cleanup on startup to allow re-run of smoke tests in the local project
* Adds a step that cleans the test resources between launches, the existing one was not cleaning postgres resources and it was failing.
* Adds while loop waiting in many @then steps to avoir unecessary wait time
* Re order some events waiting that were breaking the tests
/assign @jitendar-singh  
can you PTAL @jitendar-singh and @adambkaplan ?
The next coming PR would contain the additional smoke test verifying JENKINS_PASSWORD env var usage.

Change smoke tests so they can run in openshift-ci

---

example-plugin-development-template.yaml
openshift/imagestreams/jenkins-agent-base-centos.yaml
openshift/imagestreams/jenkins-agent-base-rhel.yaml
openshift/imagestreams/jenkins-agent-maven-centos.json
openshift/imagestreams/jenkins-agent-maven-centos.yaml
openshift/imagestreams/jenkins-agent-maven-rhel.json
openshift/imagestreams/jenkins-agent-maven-rhel.yaml
openshift/imagestreams/jenkins-agent-nodejs-centos.json
openshift/imagestreams/jenkins-agent-nodejs-centos.yaml
openshift/imagestreams/jenkins-agent-nodejs-rhel.json
openshift/imagestreams/jenkins-agent-nodejs-rhel.yaml
openshift/imagestreams/jenkins-centos.json
openshift/imagestreams/jenkins-centos.yaml
openshift/imagestreams/jenkins-rhel.json
openshift/imagestreams/jenkins-rhel.yaml
openshift/templates/jenkins-ephemeral-monitored.json
openshift/templates/jenkins-ephemeral.json
openshift/templates/jenkins-persistent-monitored.json
openshift/templates/jenkins-persistent.json
smoke/samples/maven_pipeline.yaml
smoke/samples/nodejs_pipeline.yaml

Non-groupified objects were deprecated in OCP 4.7.

Use groupified apiVersion

---

2/contrib/openshift/base-plugins.txt

Update the openshift-sync-plugin to fix bugs related to syncing BuildConfigs and other OpenShift resources.
Backport of #1358.

Bug 2037346: Update openshift-sync-plugin to 1.0.51 and various dependant plugins

---

2/contrib/openshift/base-plugins.txt

Update the openshift-sync-plugin to fix bugs related to syncing BuildConfigs and other OpenShift resources.
Backport of #1358.

Bug 2037348: Update openshift-sync-plugin to 1.0.51 and various dependant plugins

---

2/Dockerfile.localdev
2/Dockerfile.rhel7
2/Dockerfile.rhel8
2/contrib/jenkins/install-jenkins-core-plugins.sh
2/contrib/openshift/base-plugins.txt

- https://bugzilla.redhat.com/show_bug.cgi?id=2044942
- https://bugzilla.redhat.com/show_bug.cgi?id=2044846

Bug 2044942: Jenkins Fixes for CVE-2022-20617 and CVE-2022-20612

---

2/Dockerfile.localdev
2/Dockerfile.rhel7
2/Dockerfile.rhel8
2/contrib/jenkins/install-jenkins-core-plugins.sh
2/contrib/openshift/base-plugins.txt

- https://bugzilla.redhat.com/show_bug.cgi?id=2044941

Bug 2044941: Jenkins Fixes for CVE-2022-20617 and CVE-2022-20612

---

2/contrib/openshift/base-plugins.txt

Addresses the following vulnerabilities:
- CVE-2022-20613
- CVE-2022-20614
- CVE-2022-20615
- CVE-2022-20616
- CVE-2022-20618
- CVE-2022-20619
- CVE-2022-20621
- CVE-2022-23106
Updates the following plugins:
- configuration-as-code:1.55.1
- credentials-binding:1.27.1
- cloudbees-bitbucket-branch-source:746.v350d2781c184
- git-client:3.10.0
- matrix-project:1.20
- metrics:4.0.2.8.1
- openshift-login:1.0.27
- token-macro:267.vcdaea6462991

Bug 2047839: Upgrade Jenkins plugins to fix various flaws

---

2/Dockerfile.localdev
2/Dockerfile.rhel7
2/Dockerfile.rhel8
2/contrib/jenkins/install-jenkins-core-plugins.sh
2/contrib/openshift/base-plugins.txt

- https://bugzilla.redhat.com/show_bug.cgi?id=2044939

Bug 2044939: Jenkins Fixes for CVE-2022-20617 and CVE-2022-20612

---

2/Dockerfile.localdev
2/Dockerfile.rhel7
2/Dockerfile.rhel8
2/contrib/jenkins/install-jenkins-core-plugins.sh
2/contrib/openshift/base-plugins.txt

- https://bugzilla.redhat.com/show_bug.cgi?id=2044938

Bug 2044938: Jenkins Fixes for CVE-2022-20617 and CVE-2022-20612

---

.githooks/pre-commit
CONTRIBUTING.md
README.md

Add git pre commit hook that if enabled ensures that developers re-generate `bundle-plugins.txt` and commit it on `base-plugins.txt` change.
/assign @gabemontero 
/assign @adambkaplan

JNKS-269: Adds git pre-commit hook

---

2/Dockerfile
2/contrib/openshift/base-plugins.txt

- https://bugzilla.redhat.com/show_bug.cgi?id=2044943

Bug 2044943: Jenkins Fixes for CVE-2022-20617 and CVE-2022-20612

---

2/contrib/openshift/base-plugins.txt
2/contrib/openshift/bundle-plugins.txt

```
java.io.IOException: Failed to load: Pipeline Utility Steps (2.12.0)
- Update required: Script Security Plugin (1.78) to be updated to 1131.v8b_b_5eda_c328e or higher
at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:1016)
at hudson.PluginManager$2$1$1.run(PluginManager.java:535)
at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
at jenkins.model.Jenkins$5.runTask(Jenkins.java:1151)
at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecut …
```

Bug 2054822: allow Pipeline Utility Steps (2.12.0) to start

---

2/Dockerfile.localdev
2/Dockerfile.rhel7
2/Dockerfile.rhel8

Now that the bundle-plugins.txt is correctly generated and checked using CI, this PRs enables its strict usage while building the images.

JNKS-269: Use the generated bundle-plugins.txt file while building the image

---

slave-base/contrib/bin/run-jnlp-client

When you configure Kubernetes cloud configuration in Jenkins to use Websocket connection, the Kubernetes plugin adds the JENKINS_WEB_SOCKET env variable, but that variable is ignored by the agent base image and it does not add the webSocket flag.

Add support for websocket connection to Jenkins

---

2/contrib/openshift/base-plugins.txt

- CVE-2022-25173 CVE-2022-25176 CVE-2022-25180: pin workflow-cps to
2660.vb_c0412dc4e6d
- CVE-2022-25174 CVE-2022-25177 CVE-2022-25178 CVE-2022-25181
CVE-2022-25182 CVE-2022-25183 : pin workflow-cps-global-lib to
564.ve62a_4eb_b_e039
- CVE-2022-25175 CVE-2022-25179: pin workflow-multibranch to
711.vdfef37cda_816
- CVE-2022-25184: pin pipleine-build-step to 2.

Bug 2063898: [release-4.10] 2022-02-15 Security Advisory

---

2/contrib/openshift/base-plugins.txt

- CVE-2022-25173 CVE-2022-25176 CVE-2022-25180: pin workflow-cps to 2660.vb_c0412dc4e6d
- CVE-2022-25174 CVE-2022-25177 CVE-2022-25178 CVE-2022-25181 CVE-2022-25182 CVE-2022-25183 : pin workflow-cps-global-lib to 564.ve62a_4eb_b_e039
- CVE-2022-25175 CVE-2022-25179: pin workflow-multibranch to 711.vdfef37cda_816
- CVE-2022-25184: pin pipleine-build-step to 2.

Bug 2058751: [release-4.9] 2022-02-15 Security Advisory

---

2/contrib/openshift/base-plugins.txt

- CVE-2022-25173 CVE-2022-25176 CVE-2022-25180: pin workflow-cps to
2660.vb_c0412dc4e6d
- CVE-2022-25174 CVE-2022-25177 CVE-2022-25178 CVE-2022-25181
CVE-2022-25182 CVE-2022-25183 : pin workflow-cps-global-lib to
564.ve62a_4eb_b_e039
- CVE-2022-25175 CVE-2022-25179: pin workflow-multibranch to
711.vdfef37cda_816
- CVE-2022-25184: pin pipleine-build-step to 2.

Bug 2058750: [release-4.8] 2022-02-15 Security Advisory

---

smoke/features/jenkins-ephemeral.feature
smoke/features/jenkins-maven-agent.feature
smoke/features/jenkins-nodejs-agent.feature
smoke/features/jenkins-teardown-ephemeral.feature
smoke/features/persistent-jenkins.feature
smoke/features/persistent-maven-agent.feature
smoke/features/persistent-nodejs-agent.feature
smoke/features/persistent-test.feature
smoke/features/sidecar-pattern-jenkins.feature
smoke/features/stress-test.feature

Github integration with polarion identifies the test cases with unique ids. Introducing IDs for smoke tests.

JKNS-271 : Adding Test case Ids to ease polarion integration for jenkins

---

2/contrib/s2i/run
README.md
openshift/templates/jenkins-ephemeral-monitored.json
openshift/templates/jenkins-ephemeral.json
openshift/templates/jenkins-persistent-monitored.json
openshift/templates/jenkins-persistent.json
slave-base/contrib/bin/run-jnlp-client

without defaulting so, none of our Jenkins related JVMs will come up on a FIPS enabled node, failing with something like
```
SEVERE: FIPS mode: only SunJSSE TrustManagers may be used
java.security.KeyManagementException: FIPS mode: only SunJSSE TrustManagers may be used
at java.base/sun.security.ssl.SSLContextImpl.chooseTrustManager(SSLContextImpl.java:133)
at java.base/sun.security.ssl.SSLContextImpl.engineInit(SSLContextImpl.java:95)
at java.base/javax.net.ssl.SSLContext.init(SSLContext.java:297)
```

Bug 2066019: set necessary JVM args to allow jenkins JVM to come up on a FIPS node

---

openshift/imagestreams/jenkins-agent-base-rhel.json
openshift/imagestreams/jenkins-agent-base-rhel.yaml
openshift/imagestreams/jenkins-rhel.json
openshift/imagestreams/jenkins-rhel.yaml

after this merges, and openshift/library's cron job picks it up, the we'll do the official library sync for jenkins in https://github.com/openshift/cluster-samples-operator/pull/416 and be done with OCP for this
/assign @coreydaley 
/assign @jkhelil

JKNS-289: complete switch from ocp payload to cpaas images for both jenkins and base agent ocp images

---

openshift/imagestreams/jenkins-centos.json

long term if we need this for okd we'll push permanent tags to quay.io/redhat-developer

JNKS-287: cannot use specific image refs with okd; quay.io prunes too often

---

openshift/imagestreams/jenkins-agent-maven-ocp.json
openshift/imagestreams/jenkins-agent-maven-okd.json
openshift/imagestreams/jenkins-agent-nodejs-ocp.json
openshift/imagestreams/jenkins-agent-nodejs-okd.json

We cannot remove them while the images are only deprecated.  We have to wait to remove until the images are EOL.  This corrects my overzealous removal with https://github.com/openshift/jenkins/pull/1414
That said, they now point to the latest 4.10 versions at registry.redhat.io and quay.io, vs. older versions (which were overridden by samples operator).

JNKS-289: return agent-maven / agent-nodejs imagestreams

---

2/contrib/jenkins/install-plugins.sh
2/contrib/openshift/base-plugins.txt
2/contrib/openshift/bundle-plugins.txt

4.10 image is not starting correctly because of incorrect version of matrix-project plugin

Bug 2095620: Bump matrix-project plugin to 1.20

---

slave-base/contrib/bin/run-jnlp-client

Jenkins enforces trailing slash [1] and appending the second one is causing troubles on our OCP clusters when custom OCP route with CNAME is used. Some clients (recent versions of Chrome and curl) that use HTTP/2 fail [2].
[1] https://github.com/jenkinsci/jenkins/blob/master/core/src/main/java/jenkins/model/JenkinsLocationConfiguration.java#L140
[2]
```
Downloading https://<URL>//jnlpJars/remoting.jar ...
curl: (92) HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
```

Bug 2096186: Avoid double slashes trailing in remoting.jar

---

2/contrib/openshift/base-plugins.txt
2/contrib/openshift/bundle-plugins.txt

Update to newer version which does not use the groovy-sandbox library

OCPBUGS-655: Update blueocean-autofavorite to 1.2.5

---

slave-base/Dockerfile.rhel8

Whenever jenkins jobs and commands are run, logs are filled with below warning:
```
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8) <---
```
Installing the glibc language package solves the problem.
Bug https://issues.redhat.com/browse/OCPBUGS-1037

[release-4.10] OCPBUGS-1037: Install glibc language package to remove `setLocale` warning

---

2/contrib/openshift/base-plugins.txt
2/contrib/openshift/bundle-plugins.txt
OWNERS

Force git-server to an earlier version  to ensure that we get version of sshd matching the embedded in jenkins 2.361.1

OCPBUGS-2099: Force git-server to an earlier version

---

2/Dockerfile.localdev
2/Dockerfile.rhel7
slave-base/Dockerfile.localdev
slave-base/Dockerfile.rhel7
slave-base/Dockerfile.rhel8

Whenever jenkins jobs and commands are run, logs are filled with below warning:
```
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8) <---
```
Installing the glibc language package solves the problem.
Bug https://issues.redhat.com/browse/OCPBUGS-1757

[release-4.9] OCPBUGS-1757: Install glibc language package to remove `setLocale` warning

---

2/contrib/openshift/base-plugins.txt
2/contrib/openshift/bundle-plugins.txt

- CVE-2022-43405: `pipeline-groovy-lib` bumped to `612.614.v48dcb_f62a_640`
- CVE-2022-43402: `workflow-cps` bumped to `2803.v1a_f77ffcc773`
- CVE-2022-43407: `pipeline-input-step` bumped to `456.vd8a_957db_5b_e9`
- CVE-2022-43408: `pipeline-rest-api` bumped to `2.27`
- CVE-2022-43409: `workflow-support` bumped to `839.v35e2736cfd5c`
- CVE-2022-43403, CVE-2022-43404, CVE-2022-43401:  `script-security` bumped to `1184.v85d16b_d851b_3`
- CVE-2022-45047: `mina-sshd-api-{core,common}` bumped to `2.9.2-50.va_0e1f42659a_a`
- CVE-2022-43406: `workflow-cps-global-lib` already on `588.v576c103a_ff86`
- CVE-2022-25857: `snakeyaml-api` already on `1.32-86.ve3f030a_75631`
- CVE-2022-30954, CVE-2022-30953: `blueocean` already on `1.25.8`
- CVE-2021-26291: not applicable

OCPBUGS-4094: Various CVEs September/2022

---

2/Dockerfile.rhel8
agent-maven/Dockerfile.rhel8
agent-nodejs-10/Dockerfile.rhel8
agent-nodejs-12/Dockerfile.rhel8
slave-base/Dockerfile.rhel8

`slave-base/Dockerfile.rhel8` should label with rhel8, which is labeled with rhel7 currently.

OCPBUGS-8437: Fix labels for jenkins-slave-base-rhel8

---

2/contrib/openshift/base-plugins.txt
2/contrib/openshift/bundle-plugins.txt

Mitigates:
- https://github.com/advisories/GHSA-9j65-3f2q-8q2r
- https://github.com/advisories/GHSA-ph74-8rgx-64c5
Fixes Mailer plugin breaking update issue
Breaking changes
Migrate to Jakarta Mail (https://github.com/jenkinsci/mailer-plugin/pull/144) @basil
Related plugin releases
The following plugins must be upgraded in lockstep:
[Mailer 435.v79ef3972b_5c7](https://github.com/jenkinsci/mailer-plugin/releases/tag/435.v79ef3972b_5c7)
[Pipeline: Basic Steps 980.v82219a_ed188e](https://github.com/jenkinsci/workflow-basic-steps-plugin/releases/tag/980.v82219a_ed188e)
[Email Extension 2.90](https://github.com/jenkinsci/email-ext-plugin/releases/tag/email-ext-2.90)
Failure to upgrade all three plugins in lockstep will result in linkage errors. …

OCPBUGS-11158,OCPBUGS-7575,OCPBUGS-7572: Various issues

---

scripts/verify-jenkins-on-openshift.sh

The script `verify-jenkins-on-openshift.sh` takes the following inputs:
- Cluster's API Server URL
- OpenShift Username & Password
- Jenkins Image
- SHA of the relevant commit (This is requested at a later stage, let me know, if we should input this at the beginning itself (with other variables)).
& Automates the following tasks:
- Pulling the (provided) CPaas image, tagging & pushing it to `quay.io/pipeline-integrations`.
- Logging in to an OpenShift cluster, creating a project & deploying jenkins pod using the provided image.
- Once the pod is ready, executes [verify-jenkins.sh](https://github.com/openshift/jenkins/blob/master/scripts/verify-jenkins.sh) within the pod & redirects the output in a file on local machine.
- Checks for errors in the output file, if found, reports.

[JKNS-344] Second phase of self-verification process for Jenkins

---

openshift/templates/jenkins-ephemeral.json
openshift/templates/jenkins-persistent.json
smoke/features/steps/openshift.py

Reverts openshift/jenkins#1706, which switched the Jenkins templates to use `Deployment` from `DeploymentConfig`. This was an incomplete and left the template with an invalid pod template spec (container image was empty).

OCPTOOLS-393: Revert Incomplete Template Update

---

2/contrib/s2i/run
slave-base/contrib/bin/run-jnlp-client

Fixes #1712
Removed code from #1666 is added back to allow use of other Java versions.

JKNS-397: Fix USE_JAVA_VERSION environment variable

---

2/contrib/openshift/base-plugins.txt
2/contrib/openshift/bundle-plugins.txt

Fixes the following CVE(s):
* CVE-2024-34144
* CVE-2024-34145

OCPTOOLS-406: Bump Script Security Plugin to 1336.vf33a_a_9863911

---

2/Dockerfile.localdev
2/Dockerfile.rhel8
2/contrib/s2i/run
BASIC_USAGE.md
CONTRIBUTING.md
openshift/templates/jenkins-ephemeral-monitored.json
openshift/templates/jenkins-ephemeral.json
openshift/templates/jenkins-persistent-monitored.json
openshift/templates/jenkins-persistent.json
slave-base/Dockerfile.localdev
slave-base/Dockerfile.rhel8
slave-base/contrib/bin/run-jnlp-client

- Remove java-11-openjdk and java-11-openjdk-headless from Dockerfiles
- Remove java 11 and jdk 11 from comment, doc, s2i and template files
Signed-off-by: Vinu K <kevy.vinu@gmail.com>
(cherry picked from commit f75c532ddc8c69d9bfe88f29bd51ee11692954fb)

JKNS-500: Remove java 11 usage

---

2/contrib/jenkins/install-jenkins-core-plugins.sh

The CI test are failing as dnf repo search location changed to `/etc/yum.repos.art/ci` dir in CI through PR [#5974](https://github.com/openshift-eng/ocp-build-data/pull/5974).

[JKNS-618]: Update jenkins dnf repo to art-ci

---

go.mod

- Bump go version to `1.21.0` in go.mod

release-4.13: Bump go version to 1.21.0 in go.mod
